/**
 * ─────────────────────────────────────────────────────────────────────────────
 *  TranStudio — shared type contracts
 * ─────────────────────────────────────────────────────────────────────────────
 *  These types are the spine of the whole app. Every layer (scraper, player,
 *  sync engine, Gemini, clipper, exporters) speaks only in these shapes, so
 *  each step of the build can be written and tested independently.
 */

/* ═══════════════════════════════ 1. TRANSCRIPT ═════════════════════════════ */

/**
 * A single caption line exactly as `youtube-transcript` hands it back.
 * `offset`/`duration` are in **seconds** (YouTube returns milliseconds; we
 * normalize at the edge so the rest of the app never multiplies by 1000).
 */
export interface RawTranscriptSegment {
  text: string;
  duration: number;
  offset: number;
}

/** A decoratable caption line used by the UI (sync engine + clip mapper). */
export interface TranscriptSegment extends RawTranscriptSegment {
  /** Stable index — doubles as the array position and React key. */
  id: number;
  /** `offset + duration`, clamped at fetch time. */
  end: number;
  /** Character count, precomputed for virtualized height estimates. */
  charCount: number;
}

/** Where the captions came from — surfaced in the UI for transparency. */
export type TranscriptSource =
  | "youtube-transcript" /* npm scraper (InnerTube, falls back to web page) */
  | "innertube"
  | "web-page"
  | "browser" /* fetched from the visitor's own connection (CORS permitting) */
  | "paste" /* pasted from YouTube's transcript panel or a subtitle file */
  | "demo";

/** Everything the app needs to render + export + feed Gemini. */
export interface TranscriptPayload {
  videoId: string;
  /** Best-effort display title; absent for caption-only API callers. */
  title?: string;
  url: string;
  /** BCP-47-ish code YouTube reported, e.g. "en", "auto". */
  language: string;
  languageLabel: string;
  /** True when YouTube served auto-generated (ASR) captions. */
  isAutoGenerated: boolean;
  source: TranscriptSource;
  segments: TranscriptSegment[];
  /** Which fetch strategy produced this (e.g. "innertube:android"). */
  strategy?: string;
  /** Flat, timestamp-free text — the cheapest thing to send to the LLM. */
  text: string;
  wordCount: number;
  characterCount: number;
  /** Last segment end, i.e. the spoken length of the video. */
  durationSeconds: number;
  /** ISO date string; used for export headers + cache freshness. */
  fetchedAt: string;
}

/** Lightweight metadata pulled alongside the transcript. */
export interface VideoMetadata {
  videoId: string;
  url: string;
  title?: string;
  author?: string;
  thumbnailUrl: string;
  /** ISO-8601 duration from oEmbed/HTML when available (best effort). */
  durationSeconds?: number;
  /** Deep-link timestamp in seconds from `?t=`/`&start=`. */
  startAt?: number;
}

/** Error taxonomy so the UI can show a *useful* message, never a stack trace. */
export type TranscriptErrorCode =
  | "invalid-url"
  | "not-found"
  | "disabled"
  | "empty"
  | "too-many-requests"
  | "blocked"
  | "network"
  | "unknown";

export type FetchTranscriptResult =
  | {
      ok: true;
      transcript: TranscriptPayload;
      metadata: VideoMetadata;
      /** Extra context for the UI, e.g. why a demo transcript was served. */
      notice?: string;
      /** Per-strategy attempt log (mirrors the same field on failures). */
      diagnostics?: string[];
    }
  | {
      ok: false;
      error: TranscriptErrorCode;
      message: string;
      /** Present when we could still resolve the video id (e.g. bad captions). */
      videoId?: string;
      hint?: string;
      /** Exactly which strategies were tried, and what each one said. */
      diagnostics?: string[];
    };

/* ═══════════════════════════ 2. GEMINI CHAT ════════════════════════════════ */

export type ChatRole = "user" | "assistant" | "system";

/** How long a reply may get — mapped to maxOutputTokens / thinking config. */
export type ChatMode = "chat" | "clips" | "summary" | "chapters";

export type ChatMessageStatus = "pending" | "streaming" | "done" | "error";

export interface ChatMessage {
  id: string;
  role: ChatRole;
  content: string;
  createdAt: number;
  status: ChatMessageStatus;
  /** Set on the turn that produced a clip plan (Step 5). */
  clipPlan?: ClipPlan;
  /** Present when `status === "error"`. */
  error?: string;
  /** Machine-readable provider category for the recoverable error state. */
  errorCode?: string;
  /** Whether the UI should offer a same-request retry action. */
  retryable?: boolean;
  /** Model that produced the turn (for the "which model answered" footer). */
  model?: string;
  /** Provider that produced the turn. */
  provider?: AiProviderId;
  /** Routing note shown quietly under the answer. */
  note?: string;
  /** Mode the turn was asked in (clips turns render the clip studio). */
  mode?: ChatMode;
  /** Seconds the model spent (nice for the token-efficiency readout). */
  latencyMs?: number;
}

/** Trimmed history sent back to the server so prompts stay cheap. */
export interface ChatHistoryEntry {
  role: ChatRole;
  content: string;
}

export interface ChatRequest {
  mode: ChatMode;
  message: string;
  /** Compact transcript payload: flat text + segments (only what the mode needs). */
  transcript: ChatTranscriptContext;
  history: ChatHistoryEntry[];
  /** Which AI answers: "auto" (Gemini, then Groq) or a manual choice. */
  provider?: AiProviderChoice;
  /** Models that answered for this browser before — tried first, if still valid. */
  preferredModels?: Partial<Record<AiProviderId, string>>;
}

/** The free AI providers NexAI can use. */
export type AiProviderId = "gemini" | "groq";
export type AiProviderChoice = "auto" | AiProviderId;

/** GET /api/chat — which providers this installation has keys for. */
export interface AiProviderStatus {
  gemini: boolean;
  groq: boolean;
}

/** The transcript context injected into every Gemini call. */
export interface ChatTranscriptContext {
  videoId: string;
  title: string;
  durationSeconds: number;
  /** Flat text — used for `chat`/`summary` (cheapest). */
  text: string;
  /** Timestamped lines — used for `clips`/`chapters` (needs timing). */
  segments: Array<{ i: number; t: number; d: number; x: string }>;
  language: string;
}

export type ChatStreamEvent =
  | { type: "delta"; text: string }
  | {
      type: "meta";
      model: string;
      provider?: AiProviderId;
      /** A short, honest note, e.g. "Groq was busy — answered by Gemini". */
      note?: string;
    }
  | { type: "clips"; plan: ClipPlan }
  | { type: "error"; message: string; code?: string }
  | { type: "done" };

/* ═══════════════════════ 3. VIRAL CLIPPER (JSON CONTRACT) ══════════════════ */

/** The literal JSON shape Gemini is forced to return (snake_case on purpose). */
export interface RawClip {
  title: string;
  start_time: number;
  end_time: number;
  transcript_text: string;
  /** 0–100 virality score from the model. */
  viral_score: number;
  /** Optional extras — the schema allows them, the UI treats them as bonuses. */
  hook_type?: HookType | string;
  reason?: string;
  /** The first line the viewer hears — the hook, verbatim or near-verbatim. */
  hook_line?: string;
  /** A ready-to-post caption for Shorts / Reels / TikTok. */
  caption?: string;
  /** 3–6 hashtags, each starting with "#". */
  hashtags?: string[];
}

export interface ClipPlan {
  clips: RawClip[];
  /** One-paragraph "what this video is about" from the model. */
  summary?: string;
  /** Model's read on the whole video's clip-ability (0–100). */
  overall_score?: number;
}

export type HookType =
  | "hook"
  | "story"
  | "insight"
  | "funny"
  | "controversial"
  | "tutorial"
  | "emotional"
  | "data"
  | "quote"
  | "other";

/** A clip after the app has hydrated it with id, color and transcript ranges. */
export interface ViralClip extends RawClip {
  id: string;
  /** 0-based index in the plan; stable for keyboard shortcuts (1-9). */
  index: number;
  /** Assigned from `CLIP_PALETTE` — unique per clip in a plan. */
  color: ClipColor;
  /** Normalized timestamps (sorted, clamped to the real transcript length). */
  start: number;
  end: number;
  hookType: HookType;
  /** Ids of transcript segments this clip covers, in order. */
  segmentIds: number[];
  /** Inclusive/exclusive segment index bounds for O(1) lookups. */
  segmentStartIndex: number;
  segmentEndIndex: number;
  /** True when the model's timestamps were repaired by the mapper. */
  repaired?: boolean;
}

/** One entry of the fixed Tailwind palette mapped onto clips. */
export interface ClipColor {
  /** Tailwind hue name, e.g. "emerald". */
  id: string;
  /** Human label for the tooltip / legend. */
  label: string;
  /** Background tint for transcript bands: `bg-emerald-500/20`. */
  bg: string;
  /** Slightly stronger tint for hover/active states. */
  bgActive: string;
  /** Border tint for the band edge + swatch chip. */
  border: string;
  /** Fully opaque dot/accent: `bg-emerald-400`. */
  accent: string;
  /** Raw hex — used for gradients, canvas + CSS custom properties. */
  hex: string;
  /** oklch-friendly glow shadow used for hover elevation. */
  glow: string;
}

/** Fast lookup structure the transcript pane uses to paint clip bands. */
export interface ClipOverlay {
  clipId: string;
  /** Segment id → clips covering it (a segment can belong to 2+ clips). */
  bySegment: Map<number, ViralClip[]>;
  /** All clips sorted by start time (for the timeline rail). */
  sorted: ViralClip[];
}

/* ═══════════════════════════ 4. EXPORTS ════════════════════════════════════ */

export type ExportFormat = "txt" | "md" | "srt" | "vtt" | "json" | "csv";

export interface ExportOptions {
  format: ExportFormat;
  includeTimestamps: boolean;
  includeHeader: boolean;
  /** Merge caption lines into readable paragraphs (txt/md only). */
  mergeSentences?: boolean;
}

export interface ExportPreset {
  id: ExportFormat;
  label: string;
  extension: string;
  mimeType: string;
  description: string;
  supportsTimestamps: boolean;
  supportsMerging: boolean;
}

/* ═══════════════════════════ 5. SETTINGS / THEMING ═════════════════════════ */

export type ThemeId = "oled" | "cyberpunk" | "glass" | "zen";

/** Drives native `color-scheme` so scrollbars/inputs match the theme. */
export type ColorScheme = "dark" | "light";

export interface ThemeDefinition {
  id: ThemeId;
  label: string;
  tagline: string;
  /** A second line of product-facing detail for the full theme gallery. */
  detail: string;
  /** Optional caution displayed as a distinct badge in the full gallery. */
  warning?: string;
  scheme: ColorScheme;
  /** Three hex swatches for the theme picker preview. */
  swatch: [string, string, string];
  /** Readable text colour on the preview card (swatch[0] background). */
  ink: string;
  /** Featured theme shown as a "signature" card in the picker. */
  signature?: boolean;
}

export type FontFamilyId = "sans" | "serif" | "dyslexic";

export interface FontOption {
  id: FontFamilyId;
  label: string;
  /** Full CSS font stack, injected into `--transcript-font`. */
  stack: string;
  description: string;
  /** The package that self-hosts the face (keeps the app 100% offline-safe). */
  package: string;
}

export interface TypographySettings {
  fontFamily: FontFamilyId;
  /** rem units. */
  fontSize: number;
  lineHeight: number;
  letterSpacing: number;
  /** Max line length in `ch`. */
  measure: number;
}

export type ViewMode = "split" | "cinema" | "read";

export interface ViewModeDefinition {
  id: ViewMode;
  label: string;
  description: string;
}

export interface AppSettings {
  theme: ThemeId;
  typography: TypographySettings;
  viewMode: ViewMode;
  /** Auto-scroll the transcript to follow playback. */
  autoScroll: boolean;
  /** Keep the active sentence vertically centered vs. just visible. */
  centerActiveLine: boolean;
  /** Show (and use) the Gemini assistant panel. */
  sidebarOpen: boolean;
  sidebarWidth: number;
  /** Show offset badges next to transcript lines. */
  showTimestamps: boolean;
  /** Highlight clip bands in the transcript (Step 5). */
  showClipHighlights: boolean;
  /** Honour the OS "reduce motion" preference on top of our animations. */
  reduceMotion: boolean;
}

/* ═══════════════════════════ 6. PLAYER CONTRACT ════════════════════════════ */

export type PlayerStatus = "unstarted" | "playing" | "paused" | "buffering" | "ended";

/** The imperative handle every player implementation must expose. */
export interface PlaybackController {
  seekTo(seconds: number): void;
  play(): void;
  pause(): void;
  toggle(): void;
  getCurrentTime(): number;
  getDuration(): number;
  /** Loop playback between two timestamps (clip preview). */
  setLoopRange(range: ClipRange | null): void;
  setMuted(muted: boolean): void;
  isMuted(): boolean;
}

export interface ClipRange {
  start: number;
  end: number;
  clipId?: string;
}

/** Snapshot of playback, published by the player and consumed by everything. */
export interface PlaybackState {
  status: PlayerStatus;
  currentTime: number;
  duration: number;
  /** Index into `transcript.segments` whose time window contains currentTime. */
  activeSegmentIndex: number;
  playingClipId: string | null;
}

/* ═══════════════════════════ 7. TRANSPORT / UI ═════════════════════════════ */

/** Generic async state so every panel renders identical, predictable feedback. */
export type AsyncStatus = "idle" | "loading" | "streaming" | "success" | "error";

export type ToastTone = "info" | "success" | "error";

export interface Toast {
  id: string;
  message: string;
  tone: ToastTone;
  /** Optional inline action, e.g. "Retry". */
  action?: { label: string; href?: string };
}
