import { describe, expect, it } from "vitest";

import { buildCsv, buildExport, buildSrt, buildVtt, mergeIntoParagraphs } from "@/lib/export/formats";
import type { TranscriptPayload } from "@/lib/types";

const makeTranscript = (title?: string): TranscriptPayload => {
  const segments = [
    { id: 0, text: "A short cue.", offset: 0, duration: 2, end: 2, charCount: 12 },
    { id: 1, text: "The next cue continues the thought and gives it enough length to make a useful paragraph rather than a chopped subtitle.", offset: 2, duration: 4, end: 6, charCount: 112 },
  ];
  return {
    videoId: "abc123",
    ...(title ? { title } : {}),
    url: "https://youtube.com/watch?v=abc123",
    language: "en",
    languageLabel: "English",
    isAutoGenerated: false,
    source: "demo",
    segments,
    text: segments.map((segment) => segment.text).join(" "),
    wordCount: 20,
    characterCount: 130,
    durationSeconds: 6,
    fetchedAt: "now",
  };
};

describe("export formats", () => {
  it("does not make a single short cue a paragraph", () => {
    expect(mergeIntoParagraphs([makeTranscript().segments[0]])).toEqual(["A short cue."]);
  });

  it("joins caption-sized cues once a paragraph has enough substance", () => {
    expect(mergeIntoParagraphs(makeTranscript().segments)).toHaveLength(1);
  });

  it("writes valid SRT and VTT timecodes", () => {
    expect(buildSrt(makeTranscript())).toContain("00:00:00,000 --> 00:00:02,000");
    expect(buildVtt(makeTranscript())).toContain("00:00:00.000 --> 00:00:02.000");
  });

  it("quotes commas and line breaks in CSV", () => {
    expect(buildCsv({ ...makeTranscript(), segments: [{ ...makeTranscript().segments[0], text: "hello,\nworld" }] })).toContain('"hello,\nworld"');
  });

  it("uses the TranStudio filename for an untitled video", () => {
    expect(buildExport(makeTranscript(), [], { format: "txt", includeTimestamps: false, includeHeader: true, mergeSentences: true }).filename).toBe("transtudio-abc123.txt");
    expect(buildExport(makeTranscript("A useful title"), [], { format: "json", includeTimestamps: true, includeHeader: true }).filename).toBe("a-useful-title.json");
  });
});
