"use client";

/**
 * The reading surface. Wraps the caption lines in a scroll container and keeps
 * the active line marked.
 *
 * Step 2 scope: render, timestamp badges, click-to-seek.
 * Step 3 adds the auto-scroll follow, the kinetic liquid highlight and the
 * "resume following" affordance — the pure maths for those already lives in
 * `lib/youtube/sync.ts` and is unit-tested.
 */
import { useMemo, useRef } from "react";
import { AlignLeft } from "lucide-react";

import type { TranscriptSegment } from "@/lib/types";
import { formatDuration, readingMinutes } from "@/lib/utils";
import { TranscriptLine } from "@/components/workspace/TranscriptLine";
import { usePlaybackStore } from "@/stores/usePlaybackStore";
import { useSettingsStore } from "@/stores/useSettingsStore";
import { useTranscriptStore } from "@/stores/useTranscriptStore";

interface TranscriptPaneProps {
  className?: string;
}

export function TranscriptPane({ className }: TranscriptPaneProps) {
  const transcript = useTranscriptStore((s) => s.transcript);
  const showTimestamps = useSettingsStore((s) => s.showTimestamps);
  const activeIndex = usePlaybackStore((s) => s.activeSegmentIndex);
  const seekTo = usePlaybackStore((s) => s.seekTo);

  const scrollRef = useRef<HTMLDivElement>(null);

  const segments: TranscriptSegment[] = transcript?.segments ?? [];
  const forceHours = (transcript?.durationSeconds ?? 0) >= 3600;

  const stats = useMemo(() => {
    if (!transcript) return null;
    return {
      lines: transcript.segments.length,
      words: transcript.wordCount,
      reading: readingMinutes(transcript.wordCount),
      duration: formatDuration(transcript.durationSeconds),
    };
  }, [transcript]);

  return (
    <section className={className} aria-label="Transcript">
      {/* ── Header ─────────────────────────────────────────────────────── */}
      <header className="flex flex-wrap items-center justify-between gap-2 border-b border-line px-3 py-2">
        <div className="flex items-center gap-2">
          <AlignLeft className="h-3.5 w-3.5 text-accent" />
          <h2 className="text-[12px] font-semibold tracking-wide text-ink-soft uppercase">
            Transcript
          </h2>
          {transcript?.isAutoGenerated && <span className="chip !py-0 !text-[9px]">auto</span>}
          {transcript?.strategy && (
            <span
              className="chip !py-0 !text-[9px]"
              title={`Fetched via ${transcript.strategy}`}
            >
              {transcript.strategy.replace("innertube:", "")}
            </span>
          )}
          {transcript?.languageLabel && (
            <span className="chip !py-0 !text-[9px]">{transcript.languageLabel}</span>
          )}
        </div>

        {stats && (
          <p className="font-mono text-[11px] text-ink-faint tabular-nums">
            {stats.lines} lines · {stats.words.toLocaleString()} words · {stats.duration} ·{" "}
            {stats.reading} min read
          </p>
        )}
      </header>

      {/* ── Lines ──────────────────────────────────────────────────────── */}
      <div
        ref={scrollRef}
        className="fade-y min-h-0 flex-1 overflow-y-auto overscroll-contain px-2 py-3 sm:px-3"
      >
        {segments.length === 0 ? (
          <p className="px-3 py-8 text-center text-[13px] text-ink-faint">
            No transcript loaded yet.
          </p>
        ) : (
          <ol className="reading-type mx-auto flex flex-col gap-[0.35em]">
            {segments.map((segment) => (
              <TranscriptLine
                key={segment.id}
                segment={segment}
                active={segment.id === activeIndex}
                showTimestamp={showTimestamps}
                forceHours={forceHours}
                onSeek={seekTo}
              />
            ))}
          </ol>
        )}
      </div>
    </section>
  );
}
