import { describe, expect, it } from "vitest";

import { MIN_CLIP_SECONDS, buildClipOverlay, mapClipPlan } from "@/lib/clips/map";
import type { ClipPlan, TranscriptPayload } from "@/lib/types";

const segments = Array.from({ length: 6 }, (_, index) => ({
  id: index,
  text: `Caption line ${index}`,
  offset: index * 10,
  duration: 10,
  end: index * 10 + 10,
  charCount: 15,
}));

const transcript: TranscriptPayload = {
  videoId: "verify",
  url: "",
  language: "en",
  languageLabel: "English",
  isAutoGenerated: false,
  source: "demo",
  segments,
  text: segments.map((segment) => segment.text).join(" "),
  wordCount: 18,
  characterCount: 100,
  durationSeconds: 60,
  fetchedAt: "now",
};

const plan = (...clips: ClipPlan["clips"]): ClipPlan => ({ clips });
const clip = (start_time: number, end_time: number, title = "Moment") => ({
  title,
  start_time,
  end_time,
  transcript_text: "model quote",
  viral_score: 80,
});

describe("clip mapping", () => {
  it("repairs believable millisecond timestamps", () => {
    const result = mapClipPlan(plan(clip(8_000, 24_000)), transcript);
    expect(result).toHaveLength(1);
    expect(result[0].start).toBe(0);
    expect(result[0].end).toBe(30);
    expect(result[0].repaired).toBe(true);
  });

  it("does not turn a genuine impossible overshoot into a tiny millisecond clip", () => {
    const result = mapClipPlan(plan(clip(52, 400)), transcript);
    expect(result).toEqual([]);
    expect(MIN_CLIP_SECONDS).toBeGreaterThan(0);
  });

  it("clamps an end overshoot and snaps both bounds to caption lines", () => {
    const result = mapClipPlan(plan(clip(12, 58)), transcript);
    expect(result[0].start).toBe(10);
    expect(result[0].end).toBe(60);
    expect(result[0].transcript_text).toBe("Caption line 1 Caption line 2 Caption line 3 Caption line 4 Caption line 5");
  });

  it("drops a range that cannot be located", () => {
    const result = mapClipPlan(plan(clip(100, 120)), transcript);
    expect(result).toHaveLength(0);
  });

  it("keeps palette order while sorting the hydrated clips by start", () => {
    const result = mapClipPlan(plan(clip(40, 49, "later"), clip(2, 9, "first")), transcript);
    expect(result.map((item) => item.title)).toEqual(["first", "later"]);
    expect(result.find((item) => item.title === "later")?.color.id).toBe("rose");
    expect(result.find((item) => item.title === "first")?.color.id).toBe("red");
  });

  it("creates a segment-to-clip overlay", () => {
    const result = mapClipPlan(plan(clip(2, 19)), transcript);
    const overlay = buildClipOverlay(result);
    expect(overlay.bySegment.get(0)?.[0].id).toBe(result[0].id);
    expect(overlay.bySegment.get(1)?.[0].id).toBe(result[0].id);
  });
});
