/**
 * ─────────────────────────────────────────────────────────────────────────────
 *  Caption fetching — multi-client, format-agnostic, self-diagnosing.
 * ─────────────────────────────────────────────────────────────────────────────
 *  Strategy ladder (first success wins):
 *    1. Innertube `player` as WEB          — richest response, but often hides
 *                                            captions from datacenter IPs.
 *    2. Innertube `player` as ANDROID      — no consent wall; usually works
 *                                            where WEB is throttled.
 *    3. Innertube `player` as WEB_EMBEDDED — different quota bucket again.
 *    4. Watch-page HTML → ytInitialPlayerResponse (with consent cookies).
 *    5. `timedtext` fetch, format detected from the body (json3 / srv3 /
 *       classic XML / WebVTT) instead of assumed.
 *
 *  Every attempt appends a diagnostic line, and those lines are surfaced in the
 *  UI and in `/status`, so a failure is never a mystery again.
 */
import type { TranscriptSegment } from "@/lib/types";
import { normalizeSegments } from "@/lib/youtube/normalize";
import {
  CONSENT_COOKIE,
  INNERTUBE_CLIENTS,
  PRIMARY_CLIENT,
  playerRequest,
  timedTextHeaders,
  unsignedTimedTextUrl,
  withCaptionFormat,
  type InnertubeClient,
} from "@/lib/youtube/clients";
import {
  parseCaptionBody,
  readPlayerResponse,
  extractInitialPlayerResponse,
  type PlayerResponseInfo,
  type TimeUnit,
} from "@/lib/youtube/parse";
import { normalizeCaption } from "@/lib/utils";

export interface Diagnostic {
  strategy: string;
  ok: boolean;
  detail: string;
}

export interface DirectCaptionSuccess {
  ok: true;
  segments: TranscriptSegment[];
  language: string;
  languageLabel: string;
  isAutoGenerated: boolean;
  /** e.g. "innertube:android" or "watch-page". */
  strategy: string;
  format: string;
  /** Unit the source body used before normalisation (json3/srv3 → ms). */
  unit: TimeUnit;
  title?: string;
  author?: string;
  durationSeconds?: number;
  diagnostics: Diagnostic[];
}

export interface DirectCaptionFailure {
  ok: false;
  diagnostics: Diagnostic[];
  /**
   * True when the failure looks like the *environment* (bot wall, consent,
   * rate limit, no network) rather than the video itself — the UI uses this to
   * decide between an error and an honest demo fallback.
   */
  environmentFailure: boolean;
  /** A definite verdict from YouTube about the video, when we got one. */
  videoUnavailable?: string;
}

export type DirectCaptionResult = DirectCaptionSuccess | DirectCaptionFailure;

export interface FetchCaptionsOptions {
  lang?: string;
  /** Budget for a single request. */
  timeoutMs?: number;
  /**
   * Budget for the whole ladder. Without it, five blocked clients at 9s each
   * would leave the user staring at a spinner for the best part of a minute;
   * with it we give up early and say what was tried.
   */
  deadlineMs?: number;
  signal?: AbortSignal;
  /**
   * Fetch implementation to use. `fetchTranscriptForUrl` injects one that
   * rewrites requests through `TRANSCRIPT_PROXY_URL`, so a host whose IP range
   * YouTube throttles can route around it — including the Innertube calls,
   * which would otherwise bypass the proxy entirely.
   */
  fetcher?: typeof fetch;
}

/** Per-request and whole-ladder budgets. */
const DEFAULT_TIMEOUT_MS = 6_000;
/**
 * Whole-ladder ceiling. Every rung logs its own attempt, so giving up early
 * still produces a full explanation — and the user never waits a minute for a
 * verdict we could have reached faster.
 */
const DEFAULT_DEADLINE_MS = 15_000;

/** A deadline counts down and clamps each individual request to it. */
function makeBudget(options: FetchCaptionsOptions) {
  const startedAt = Date.now();
  const deadlineMs = options.deadlineMs ?? DEFAULT_DEADLINE_MS;
  const elapsed = () => Date.now() - startedAt;
  return {
    elapsed,
    expired: () => elapsed() >= deadlineMs,
    /** Per-request timeout, never allowed to outlive the deadline. */
    slice: () => Math.max(1_500, Math.min(options.timeoutMs ?? DEFAULT_TIMEOUT_MS, deadlineMs - elapsed())),
  };
}

/* ─────────────────────────────── helpers ────────────────────────────────── */

async function fetchWithTimeout(
  input: string,
  init: RequestInit,
  timeoutMs: number,
  external?: AbortSignal,
  fetcher: typeof fetch = fetch,
): Promise<Response> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  const relay = () => controller.abort();
  external?.addEventListener("abort", relay, { once: true });

  try {
    return await fetcher(input, { ...init, signal: controller.signal, cache: "no-store" });
  } finally {
    clearTimeout(timer);
    external?.removeEventListener("abort", relay);
  }
}

/**
 * Choose the most useful caption track: a manual track in the preferred
 * language, else a manual track, else ASR.
 */
export function pickTrack(
  tracks: PlayerResponseInfo["captionTracks"],
  preferredLanguage?: string,
) {
  if (tracks.length === 0) return undefined;

  const manual = tracks.filter((track) => track.kind !== "asr");
  const pool = manual.length > 0 ? manual : tracks;

  if (preferredLanguage) {
    const wanted = preferredLanguage.toLowerCase();
    const exact = pool.find((track) => track.languageCode.toLowerCase() === wanted);
    if (exact) return exact;
    const base = wanted.split("-")[0];
    const prefixed = pool.find((track) =>
      track.languageCode.toLowerCase().startsWith(base),
    );
    if (prefixed) return prefixed;
  }

  return pool.find((track) => track.languageCode.toLowerCase().startsWith("en")) ?? pool[0];
}

/** Signals that the *server* is being blocked, not that the video is broken. */
const ENVIRONMENT_SIGNALS = [
  "not a bot",
  "sign in to confirm",
  "login_required",
  "consent",
  "too many requests",
  "rate limit",
  "429",
  "unusual traffic",
  "enotfound",
  "econnrefused",
  "fetch failed",
  "network",
  "timeout",
  "aborted",
];

function looksEnvironmental(text: string): boolean {
  const lowered = text.toLowerCase();
  return ENVIRONMENT_SIGNALS.some((signal) => lowered.includes(signal));
}

/** A definite YouTube verdict about the video (as opposed to a bot wall). */
const VIDEO_VERDICTS: Record<string, string> = {
  ERROR: "YouTube reported the video as unavailable.",
  UNPLAYABLE: "The video is not playable.",
  LOGIN_REQUIRED: "Sign-in is required to watch this video (age-restricted or private).",
  AGE_VERIFICATION_REQUIRED: "This video is age-restricted.",
  CONTENT_CHECK_REQUIRED: "This video is unavailable without sign-in.",
};

/* ─────────────────────────── timedtext fetching ─────────────────────────── */

async function fetchTimedText(
  client: InnertubeClient,
  baseUrl: string,
  options: FetchCaptionsOptions,
  timeoutMs?: number,
): Promise<
  | { ok: true; segments: TranscriptSegment[]; format: string; unit: TimeUnit; language?: string }
  | { ok: false; detail: string }
> {
  const timeout = timeoutMs ?? options.timeoutMs ?? DEFAULT_TIMEOUT_MS;

  // json3 first: real JSON (no regex, no entity guessing), then srv3, then vtt.
  const formats = ["json3", "srv3", "vtt"] as const;
  const failures: string[] = [];

  for (const format of formats) {
    const url = withCaptionFormat(baseUrl, format);
    try {
      const response = await fetchWithTimeout(
        url,
        { headers: timedTextHeaders(client) },
        timeout,
        options.signal,
        options.fetcher,
      );

      if (!response.ok) {
        failures.push(`${format}: HTTP ${response.status}`);
        continue;
      }

      const body = await response.text();
      if (!body.trim()) {
        failures.push(`${format}: empty body`);
        continue;
      }

      const parsed = parseCaptionBody(body);
      if (parsed.empty) {
        failures.push(`${format}: parsed as ${parsed.format} but no text`);
        continue;
      }

      // Explicit unit from the parser — no ms/s guessing for known formats.
      const normalized = normalizeSegments(parsed.segments, { forceUnit: parsed.unit });
      if (normalized.segments.length === 0) {
        failures.push(`${format}: normalised to zero segments`);
        continue;
      }

      return {
        ok: true,
        segments: normalized.segments,
        format: parsed.format,
        unit: parsed.unit,
      };
    } catch (error) {
      failures.push(`${format}: ${error instanceof Error ? error.message : "error"}`);
    }
  }

  return { ok: false, detail: failures.join("; ") };
}

/* ───────────────────────── Innertube player POSTs ───────────────────────── */

async function fetchPlayerResponse(
  client: InnertubeClient,
  videoId: string,
  options: FetchCaptionsOptions,
  timeoutMs: number,
): Promise<PlayerResponseInfo> {
  const request = playerRequest(client);
  const response = await fetchWithTimeout(
    request.url,
    {
      method: "POST",
      headers: request.headers,
      body: JSON.stringify({
        context: client.context,
        videoId,
        contentCheckOk: true,
        racyCheckOk: true,
      }),
    },
    timeoutMs,
    options.signal,
    options.fetcher,
  );

  if (!response.ok) {
    throw new Error(`player HTTP ${response.status}`);
  }

  return readPlayerResponse(await response.json());
}

/* ─────────────────────── unsigned timedtext (no player) ─────────────────── */

/**
 * Some manual caption tracks are served by `api/timedtext` without any signed
 * URL. It costs one request and needs no player response, which makes it a
 * useful independent rung for servers whose IPs are challenged.
 */
async function fetchFromUnsignedTimedText(
  videoId: string,
  options: FetchCaptionsOptions,
  diagnostics: Diagnostic[],
  timeoutMs: number,
): Promise<DirectCaptionSuccess | null> {
  const preferred = options.lang?.toLowerCase();
  // Preferred language (plus its base form), then English, manual before ASR.
  const candidates = Array.from(
    new Set(
      [preferred, preferred?.split("-")[0], "en"].filter(
        (value): value is string => Boolean(value),
      ),
    ),
  );

  const failures: string[] = [];

  for (const lang of candidates) {
    for (const asr of [false, true]) {
      try {
        const response = await fetchWithTimeout(
          unsignedTimedTextUrl(videoId, lang, asr),
          { headers: timedTextHeaders(PRIMARY_CLIENT) },
          timeoutMs,
          options.signal,
          options.fetcher,
        );
        if (!response.ok) {
          failures.push(`${lang}${asr ? "(asr)" : ""}: HTTP ${response.status}`);
          continue;
        }

        const body = await response.text();
        if (!body.trim()) {
          failures.push(`${lang}${asr ? "(asr)" : ""}: empty`);
          continue;
        }

        const parsed = parseCaptionBody(body);
        if (parsed.empty) {
          failures.push(`${lang}${asr ? "(asr)" : ""}: ${parsed.format} but no text`);
          continue;
        }

        const normalized = normalizeSegments(parsed.segments, { forceUnit: parsed.unit });
        if (normalized.segments.length === 0) {
          failures.push(`${lang}${asr ? "(asr)" : ""}: normalised to zero segments`);
          continue;
        }

        diagnostics.push({
          strategy: "timedtext:unsigned",
          ok: true,
          detail: `${parsed.format}, ${normalized.segments.length} lines, lang=${lang}${asr ? " (asr)" : ""}`,
        });

        return buildSuccess({
          info: { status: "OK" },
          track: { languageCode: lang, ...(asr ? { kind: "asr" } : {}) },
          segments: normalized.segments,
          format: parsed.format,
          unit: parsed.unit,
          strategy: "timedtext:unsigned",
          diagnostics,
        });
      } catch (error) {
        failures.push(`${lang}${asr ? "(asr)" : ""}: ${error instanceof Error ? error.message : "error"}`);
      }
    }
  }

  diagnostics.push({
    strategy: "timedtext:unsigned",
    ok: false,
    detail: failures.slice(0, 3).join("; ") || "no unsigned caption track",
  });
  return null;
}

/* ───────────────────────────── watch page ───────────────────────────────── */

async function fetchFromWatchPage(
  videoId: string,
  options: FetchCaptionsOptions,
  diagnostics: Diagnostic[],
  timeoutMs: number,
): Promise<DirectCaptionSuccess | null> {
  const html = await (async () => {
    try {
      const response = await fetchWithTimeout(
        `https://www.youtube.com/watch?v=${videoId}&bpctr=9999999999&has_verified=1&hl=en`,
        {
          headers: {
            "user-agent": PRIMARY_CLIENT.headers["user-agent"],
            "accept-language": "en-US,en;q=0.9",
            cookie: CONSENT_COOKIE,
          },
        },
        timeoutMs,
        options.signal,
        options.fetcher,
      );
      if (!response.ok) return null;
      return await response.text();
    } catch {
      return null;
    }
  })();

  if (!html) {
    diagnostics.push({ strategy: "watch-page", ok: false, detail: "page fetch failed" });
    return null;
  }

  const player = extractInitialPlayerResponse(html);
  if (!player) {
    diagnostics.push({
      strategy: "watch-page",
      ok: false,
      detail: html.includes("consent")
        ? "consent/bot page returned (no player response in HTML)"
        : "no ytInitialPlayerResponse in HTML",
    });
    return null;
  }

  const info = readPlayerResponse(player);
  const track = pickTrack(info.captionTracks, options.lang);

  if (!track) {
    diagnostics.push({
      strategy: "watch-page",
      ok: false,
      detail: `${info.status}${info.reason ? ` (${info.reason})` : ""} · 0 caption tracks`,
    });
    return null;
  }

  const timed = await fetchTimedText(PRIMARY_CLIENT, track.baseUrl, options, timeoutMs);
  if (!timed.ok) {
    diagnostics.push({ strategy: "watch-page", ok: false, detail: `timedtext — ${timed.detail}` });
    return null;
  }

  diagnostics.push({
    strategy: "watch-page",
    ok: true,
    detail: `${timed.format}, ${timed.segments.length} lines`,
  });

  return buildSuccess({
    info,
    track,
    segments: timed.segments,
    format: timed.format,
    unit: timed.unit,
    strategy: "watch-page",
    diagnostics,
  });
}

/* ─────────────────────────────── builder ────────────────────────────────── */

function buildSuccess(args: {
  /** Player-response metadata; synthetic for strategies that never fetched one. */
  info: Pick<PlayerResponseInfo, "status" | "title" | "author" | "lengthSeconds">;
  track: { languageCode: string; name?: string; kind?: string };
  segments: TranscriptSegment[];
  format: string;
  unit: TimeUnit;
  strategy: string;
  diagnostics: Diagnostic[];
}): DirectCaptionSuccess {
  const { info, track, segments, format, unit, strategy, diagnostics } = args;
  const label = track.name ?? track.languageCode;
  const isAuto = track.kind === "asr";

  return {
    ok: true,
    segments,
    language: track.languageCode,
    languageLabel: isAuto && !/auto/i.test(label) ? `${label} (auto-generated)` : label,
    isAutoGenerated: isAuto,
    strategy,
    format,
    unit,
    ...(info.title ? { title: info.title } : {}),
    ...(info.author ? { author: info.author } : {}),
    ...(info.lengthSeconds ? { durationSeconds: info.lengthSeconds } : {}),
    diagnostics,
  };
}

/* ─────────────────────────────── entry point ────────────────────────────── */

export async function fetchCaptionsDirect(
  videoId: string,
  options: FetchCaptionsOptions = {},
): Promise<DirectCaptionResult> {
  const diagnostics: Diagnostic[] = [];
  const budget = makeBudget(options);
  let videoVerdict: string | undefined;
  let sawEmbeddedBlock = false;

  /* Strategies 1–N: Innertube as several different client identities. */
  for (const client of INNERTUBE_CLIENTS) {
    if (budget.expired()) {
      diagnostics.push({ strategy: `innertube:${client.id}`, ok: false, detail: "skipped — time budget exhausted" });
      continue;
    }

    const name = `innertube:${client.id}`;
    try {
      const info = await fetchPlayerResponse(client, videoId, options, budget.slice());

      if (info.status !== "OK" && info.status !== "LIVE_STREAM_OFFLINE") {
        const verdict = VIDEO_VERDICTS[info.status];
        if (verdict && info.status !== "LOGIN_REQUIRED") videoVerdict ??= verdict;
        diagnostics.push({
          strategy: name,
          ok: false,
          detail: `${info.status}${info.reason ? ` — ${info.reason}` : ""}`,
        });
        // A bot wall means "try the next identity"; an unavailable video is final.
        if (looksEnvironmental(info.reason ?? "") || info.status === "LOGIN_REQUIRED") {
          sawEmbeddedBlock = true;
          continue;
        }
        continue;
      }

      const track = pickTrack(info.captionTracks, options.lang);
      if (!track) {
        diagnostics.push({
          strategy: name,
          ok: false,
          detail: `OK but 0 caption tracks (captions not exposed to this client)`,
        });
        continue;
      }

      const timed = await fetchTimedText(client, track.baseUrl, options, budget.slice());
      if (!timed.ok) {
        diagnostics.push({ strategy: name, ok: false, detail: `timedtext — ${timed.detail}` });
        continue;
      }

      diagnostics.push({
        strategy: name,
        ok: true,
        detail: `${timed.format}, ${timed.segments.length} lines, lang=${track.languageCode}${track.kind === "asr" ? " (asr)" : ""}`,
      });

      return buildSuccess({
        info,
        track,
        segments: timed.segments,
        format: timed.format,
        unit: timed.unit,
        strategy: name,
        diagnostics,
      });
    } catch (error) {
      const detail = error instanceof Error ? error.message : "unknown error";
      if (looksEnvironmental(detail)) sawEmbeddedBlock = true;
      diagnostics.push({ strategy: name, ok: false, detail });
    }
  }

  /* Next: unsigned timedtext — no player round-trip needed. */
  if (!budget.expired()) {
    const fromTimedText = await fetchFromUnsignedTimedText(
      videoId,
      options,
      diagnostics,
      budget.slice(),
    );
    if (fromTimedText) return fromTimedText;
  }

  /* Last: scrape the watch page for the player response. */
  if (!budget.expired()) {
    const fromPage = await fetchFromWatchPage(videoId, options, diagnostics, budget.slice());
    if (fromPage) return fromPage;
  } else {
    diagnostics.push({ strategy: "watch-page", ok: false, detail: "skipped — time budget exhausted" });
  }

  const environmentFailure =
    sawEmbeddedBlock ||
    diagnostics.length === 0 ||
    diagnostics.every((entry) => looksEnvironmental(entry.detail));

  return {
    ok: false,
    diagnostics,
    environmentFailure,
    ...(videoVerdict ? { videoUnavailable: videoVerdict } : {}),
  };
}

/** Readable one-liner for the UI: "innertube:android → json3 (412 lines)". */
export function describeDiagnostics(diagnostics: Diagnostic[]): string[] {
  return diagnostics.map(
    (entry) => `${entry.ok ? "✓" : "✗"} ${entry.strategy} — ${entry.detail}`,
  );
}

/** Exported for the probe/status page. */
export { normalizeCaption };
