/**
 * ─────────────────────────────────────────────────────────────────────────────
 *  Demo transcript — guarantees the app is never a dead end.
 * ─────────────────────────────────────────────────────────────────────────────
 *  Two situations need this:
 *   1. Sandboxes / CI / some datacenter IPs cannot reach youtube.com at all.
 *   2. A specific video has captions disabled.
 *
 *  Rather than showing a wall of error text, TranStudio loads a real, fully
 *  formatted transcript so every downstream feature (sync, reading, exports,
 *  clipping) stays explorable. It is always labelled as a demo in the UI.
 *
 *  The script is written to *teach the product* — a viewer reading it learns
 *  what TranStudio does — and the timings are derived from word counts so the
 *  playback sync behaves exactly like real captions.
 */
import type { RawTranscriptSegment, TranscriptPayload } from "@/lib/types";
import { normalizeSegments } from "@/lib/youtube/normalize";
import { countWords } from "@/lib/utils";

/** ~2.6 spoken words per second: a natural, unhurried presenter pace. */
const WORDS_PER_SECOND = 2.6;

const DEMO_SCRIPT = `Hey — welcome to TranStudio. In the next few minutes I'll show you how to turn any YouTube video into something you can actually read.
Here's the problem. Great information is locked inside video. You can't search it, you can't skim it, and you can't quote it accurately.
So let's start by pasting a link. TranStudio pulls the captions straight from the video — no API key, no sign up, nothing to configure.
The transcript appears on the right, and every single line is a button. Click a sentence and the video jumps to that exact moment.
Now watch what happens as the video plays. The active line follows the audio, and the whole transcript scrolls itself to stay in view. You can scroll away at any time, and the moment you click back, following resumes.
If you'd rather just read, switch to Read mode and the player gets out of your way. Your place is never lost — the transcript simply expands to a comfortable reading measure.
Not everyone reads comfortably in the same typeface, so there's a Typography studio. Size, line height, line length, and an OpenDyslexic option for readers who need it.
Now for the part I'm most excited about. Ask questions about the video itself. Because the entire transcript is held in context, the assistant can summarise it, pull out the key claims, or find the one line you half remember.
And when you want to publish, hit Find Viral Clips. TranStudio scans the whole transcript and returns the most retainable moments, each one scored and timestamped.
Every clip gets its own colour, painted directly onto the transcript, so two clips sitting next to each other never blur together. Hover a clip and you get instant actions — copy the quote with its timestamps, or loop playback between the clip's start and end.
When you're done, export everything. Plain text for a language model, Markdown for your notes, SRT or VTT for your editor.
That's the whole loop. Paste a link, read what matters, clip the best moments, and take the text with you. Everything runs on free infrastructure, and nothing leaves your browser that doesn't need to.
Thanks for reading along. Now paste a real link and try it yourself.`;

/**
 * Split a script into caption-sized lines and give each one a duration derived
 * from its word count, so timings advance realistically.
 */
export function buildDemoSegments(script: string = DEMO_SCRIPT): RawTranscriptSegment[] {
  const sentences = script
    .split(/(?<=[.!?])\s+/)
    .map((sentence) => sentence.trim())
    .filter(Boolean);

  let cursor = 0.35; // small lead-in, like real captions
  const segments: RawTranscriptSegment[] = [];

  for (const sentence of sentences) {
    const words = Math.max(1, countWords(sentence));
    const duration = Number((words / WORDS_PER_SECOND).toFixed(2));

    segments.push({
      text: sentence,
      // The normalizer detects seconds from the fractional precision and
      // converts to the canonical shape, so this exercises the real code path.
      offset: Number(cursor.toFixed(2)),
      duration,
    });

    cursor += duration + 0.12; // tiny gap between lines
  }

  return segments;
}

export const DEMO_VIDEO_ID = "transtudio-demo";
export const DEMO_TITLE = "Welcome to TranStudio — read any video";
export const DEMO_AUTHOR = "TranStudio";

/** A complete, ready-to-render transcript payload for the demo script. */
export function buildDemoTranscript(): TranscriptPayload {
  const normalized = normalizeSegments(buildDemoSegments());

  return {
    videoId: DEMO_VIDEO_ID,
    url: "",
    language: "en",
    languageLabel: "English (demo)",
    isAutoGenerated: false,
    source: "demo",
    segments: normalized.segments,
    text: normalized.text,
    wordCount: normalized.wordCount,
    characterCount: normalized.characterCount,
    durationSeconds: normalized.durationSeconds,
    fetchedAt: new Date().toISOString(),
  };
}

/** Exposed for tests + the "how long is the demo" UI hint. */
export const DEMO_SEGMENT_COUNT = buildDemoSegments().length;
