import { beforeEach, describe, expect, it, vi } from "vitest";

/**
 * Hermetic tests for the fetch pipeline.
 *
 * Both network-touching modules are mocked, so these assertions hold everywhere
 * — on a laptop, on GitHub's runners (which *do* have internet) and inside a
 * sandbox like Arena's (which does not). Without the mocks, the "network is
 * blocked" tests would pass in one environment and fail in the other.
 */
const fetchTranscriptMock = vi.fn();
const fetchVideoMetadataMock = vi.fn();
const fetchCaptionsDirectMock = vi.fn();

vi.mock("youtube-transcript", () => ({
  YoutubeTranscript: {
    fetchTranscript: (...args: unknown[]) => fetchTranscriptMock(...args),
  },
}));

// The primary strategy (our own multi-client fetcher) is mocked so the ladder
// itself is testable without network access.
vi.mock("@/lib/youtube/captions", async () => {
  const actual = await vi.importActual<typeof import("@/lib/youtube/captions")>(
    "@/lib/youtube/captions",
  );
  return {
    ...actual,
    fetchCaptionsDirect: (...args: unknown[]) => fetchCaptionsDirectMock(...args),
  };
});

vi.mock("@/lib/youtube/metadata", async () => {
  const actual = await vi.importActual<typeof import("@/lib/youtube/metadata")>(
    "@/lib/youtube/metadata",
  );
  return {
    ...actual,
    fetchVideoMetadata: (...args: unknown[]) => fetchVideoMetadataMock(...args),
  };
});

const { fetchTranscriptForUrl } = await import("@/lib/youtube/fetch");

function networkError() {
  const error = new Error("fetch failed: getaddrinfo ENOTFOUND www.youtube.com");
  error.name = "TypeError";
  return error;
}

/** What `youtube-transcript` returns on its primary (milliseconds) path. */
const RAW_MS = [
  { text: "Hello and welcome", offset: 0, duration: 2200 },
  { text: "to the studio.", offset: 2200, duration: 1800 },
  { text: "Let's read a video.", offset: 4000, duration: 2000 },
];

/** A successful direct-fetch result (what captions.ts would return). */
function directSuccess() {
  return {
    ok: true as const,
    segments: [
      { id: 0, text: "Hello and welcome", offset: 0, duration: 2.2, end: 2.2, charCount: 17 },
      { id: 1, text: "to the studio.", offset: 2.2, duration: 1.8, end: 4, charCount: 14 },
      { id: 2, text: "Let's read a video.", offset: 4, duration: 2, end: 6, charCount: 19 },
    ],
    language: "en",
    languageLabel: "English",
    isAutoGenerated: false,
    strategy: "innertube:web",
    format: "json3",
    title: "A real video",
    author: "A channel",
    durationSeconds: 42,
    diagnostics: [{ strategy: "innertube:web", ok: true, detail: "json3, 3 lines" }],
  };
}

function directFailure(overrides: Record<string, unknown> = {}) {
  return {
    ok: false as const,
    diagnostics: [
      { strategy: "innertube:web", ok: false, detail: "captions not exposed to this client" },
      { strategy: "innertube:android", ok: false, detail: "fetch failed" },
    ],
    environmentFailure: true,
    ...overrides,
  };
}

beforeEach(() => {
  fetchTranscriptMock.mockReset();
  fetchVideoMetadataMock.mockReset();
  fetchCaptionsDirectMock.mockReset();
  // Default: the primary strategy fails, so the library path is exercised.
  fetchCaptionsDirectMock.mockResolvedValue(directFailure());
  fetchVideoMetadataMock.mockResolvedValue({
    videoId: "dQw4w9WgXcQ",
    url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    title: "A real video",
    author: "A channel",
    thumbnailUrl: "https://i.ytimg.com/vi/dQw4w9WgXcQ/hqdefault.jpg",
    durationSeconds: 42,
    captionTracks: [
      { languageCode: "en", name: "English", kind: undefined },
      { languageCode: "en", name: "English (auto-generated)", kind: "asr" },
    ],
    hasOnlyAutoCaptions: false,
    resolvedBy: "innertube",
  });
  delete process.env.TRANSTUDIO_DEMO_MODE;
});

describe("fetchTranscriptForUrl — validation", () => {
  it("rejects input that isn't a YouTube link without touching the network", async () => {
    const result = await fetchTranscriptForUrl("https://vimeo.com/12345");
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.error).toBe("invalid-url");
    expect(fetchTranscriptMock).not.toHaveBeenCalled();
  });
});

describe("fetchTranscriptForUrl — primary strategy", () => {
  it("uses the multi-client fetcher first and reports its strategy + diagnostics", async () => {
    fetchCaptionsDirectMock.mockResolvedValue(directSuccess());

    const result = await fetchTranscriptForUrl("https://youtu.be/dQw4w9WgXcQ");
    expect(result.ok).toBe(true);
    if (!result.ok) return;

    expect(result.transcript.strategy).toBe("innertube:web");
    expect(result.transcript.segments).toHaveLength(3);
    expect(result.transcript.languageLabel).toBe("English");
    // Metadata comes from the player response, so no extra call was needed.
    expect(result.metadata.title).toBe("A real video");
    expect(fetchVideoMetadataMock).not.toHaveBeenCalled();
    expect(result.diagnostics?.[0]).toContain("innertube:web");
  });

  it("succeeds from the ANDROID client when WEB hides captions", async () => {
    fetchCaptionsDirectMock.mockResolvedValue({
      ...directSuccess(),
      strategy: "innertube:android",
      isAutoGenerated: true,
      languageLabel: "English (auto-generated)",
    });

    const result = await fetchTranscriptForUrl("dQw4w9WgXcQ");
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.transcript.strategy).toBe("innertube:android");
    expect(result.transcript.isAutoGenerated).toBe(true);
  });

  it("falls back to the youtube-transcript library when the primary fails", async () => {
    fetchTranscriptMock.mockResolvedValue(RAW_MS);

    const result = await fetchTranscriptForUrl("dQw4w9WgXcQ");
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.transcript.strategy).toBe("youtube-transcript");
    expect(result.transcript.segments[1].offset).toBe(2.2);
  });
});

describe("fetchTranscriptForUrl — library fallback", () => {
  it("returns a normalised, seconds-based payload with metadata", async () => {
    fetchTranscriptMock.mockResolvedValue(RAW_MS);

    const result = await fetchTranscriptForUrl("https://www.youtube.com/watch?v=dQw4w9WgXcQ");
    expect(result.ok).toBe(true);
    if (!result.ok) return;

    // Milliseconds were converted to seconds (the normalizer's whole job).
    expect(result.transcript.segments[1].offset).toBe(2.2);
    expect(result.transcript.durationSeconds).toBeCloseTo(6, 5);
    // "Hello and welcome to the studio. Let's read a video." → 10 words
    expect(result.transcript.wordCount).toBe(10);
    expect(result.transcript.language).toBe("en");
    expect(result.transcript.isAutoGenerated).toBe(false);

    // Metadata is merged in for the player + export filenames.
    expect(result.metadata.title).toBe("A real video");
    expect(result.metadata.durationSeconds).toBe(42);
    expect(result.notice).toBeUndefined();
  });

  it("honours an explicit language request", async () => {
    fetchTranscriptMock.mockResolvedValue(RAW_MS);
    await fetchTranscriptForUrl("dQw4w9WgXcQ", { lang: "en" });
    expect(fetchTranscriptMock).toHaveBeenCalledWith(
      "dQw4w9WgXcQ",
      expect.objectContaining({ lang: "en" }),
    );
  });
});

describe("fetchTranscriptForUrl — environment failures", () => {
  it("falls back to the demo transcript when the failure is environmental", async () => {
    fetchTranscriptMock.mockRejectedValue(networkError());
    fetchCaptionsDirectMock.mockResolvedValue(directFailure());

    const result = await fetchTranscriptForUrl("https://youtu.be/dQw4w9WgXcQ");
    expect(result.ok).toBe(true);
    if (!result.ok) return;

    expect(result.transcript.source).toBe("demo");
    expect(result.transcript.segments.length).toBeGreaterThan(10);
    expect(result.notice).toMatch(/cannot load youtube captions|blocked/i);
    // The attempt log travels with the result so the UI can explain itself.
    expect(result.diagnostics?.length).toBeGreaterThan(0);
  });

  it("reports a real error for a private video instead of hiding behind the demo", async () => {
    fetchCaptionsDirectMock.mockResolvedValue(
      directFailure({
        environmentFailure: false,
        videoUnavailable: "YouTube reported the video as unavailable.",
      }),
    );
    fetchTranscriptMock.mockRejectedValue(
      Object.assign(new Error("unavailable"), { name: "YoutubeTranscriptVideoUnavailableError" }),
    );

    const result = await fetchTranscriptForUrl("https://youtu.be/dQw4w9WgXcQ");
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.error).toBe("not-found");
    expect(result.diagnostics?.length).toBeGreaterThan(0);
  });

  it("does not treat an ignored unavailable verdict as a problem with the video", async () => {
    fetchCaptionsDirectMock.mockResolvedValue(
      directFailure({
        environmentFailure: true,
        diagnostics: [
          { strategy: "innertube:web", ok: false, detail: "LOGIN_REQUIRED — Sign in to confirm you're not a bot" },
          {
            strategy: "diagnosis",
            ok: false,
            detail:
              'ignored an apparent "YouTube reported the video as unavailable." verdict — other identities were challenged from this host, so that response describes the IP, not the video',
          },
        ],
      }),
    );
    fetchTranscriptMock.mockRejectedValue(
      Object.assign(new Error("unavailable"), { name: "YoutubeTranscriptVideoUnavailableError" }),
    );

    const result = await fetchTranscriptForUrl("https://youtu.be/dQw4w9WgXcQ", {
      allowDemoFallback: false,
    });
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.error).toBe("blocked");
    expect(result.message).not.toMatch(/can't be played|unavailable/i);
  });

  it("reports an error instead when the demo fallback is disabled", async () => {
    fetchTranscriptMock.mockRejectedValue(networkError());

    const result = await fetchTranscriptForUrl("https://youtu.be/dQw4w9WgXcQ", {
      allowDemoFallback: false,
    });
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.error).toBe("blocked");
  });
});

describe("fetchTranscriptForUrl — video problems are NOT masked", () => {
  it("surfaces disabled captions as a real error (no demo substitution)", async () => {
    const disabled = new Error("captions disabled");
    disabled.name = "YoutubeTranscriptDisabledError";
    fetchTranscriptMock.mockRejectedValue(disabled);
    fetchCaptionsDirectMock.mockResolvedValue(
      directFailure({
        environmentFailure: false,
        diagnostics: [
          { strategy: "innertube:web", ok: false, detail: "OK but 0 caption tracks (captions not exposed to this client)" },
        ],
      }),
    );

    const result = await fetchTranscriptForUrl("https://youtu.be/dQw4w9WgXcQ");
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.error).toBe("disabled");
    expect(result.hint).toBeTruthy();
  });

  it("surfaces an empty caption track", async () => {
    fetchTranscriptMock.mockResolvedValue([]);
    fetchCaptionsDirectMock.mockResolvedValue(
      directFailure({
        environmentFailure: false,
        diagnostics: [{ strategy: "innertube:web", ok: false, detail: "0 caption tracks" }],
      }),
    );

    const result = await fetchTranscriptForUrl("https://youtu.be/dQw4w9WgXcQ");
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.error).toBe("empty");
  });

  it("surfaces a private/deleted video", async () => {
    const unavailable = new Error("unavailable");
    unavailable.name = "YoutubeTranscriptVideoUnavailableError";
    fetchTranscriptMock.mockRejectedValue(unavailable);
    fetchCaptionsDirectMock.mockResolvedValue(
      directFailure({
        environmentFailure: false,
        videoUnavailable: "YouTube reported the video as unavailable.",
      }),
    );

    const result = await fetchTranscriptForUrl("https://youtu.be/dQw4w9WgXcQ");
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.error).toBe("not-found");
  });
});

describe("fetchTranscriptForUrl — demo mode", () => {
  it("serves the demo transcript without any scraping when forced", async () => {
    process.env.TRANSTUDIO_DEMO_MODE = "1";
    const result = await fetchTranscriptForUrl("https://youtu.be/dQw4w9WgXcQ");

    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.transcript.source).toBe("demo");
    expect(fetchTranscriptMock).not.toHaveBeenCalled();
    expect(fetchCaptionsDirectMock).not.toHaveBeenCalled();
    delete process.env.TRANSTUDIO_DEMO_MODE;
  });
});
