import { beforeEach, describe, expect, it, vi } from "vitest";

/**
 * Hermetic tests for the fetch pipeline.
 *
 * Both network-touching modules are mocked, so these assertions hold everywhere
 * — on a laptop, on GitHub's runners (which *do* have internet) and inside a
 * sandbox like Arena's (which does not). Without the mocks, the "network is
 * blocked" tests would pass in one environment and fail in the other.
 */
const fetchTranscriptMock = vi.fn();
const fetchVideoMetadataMock = vi.fn();

vi.mock("youtube-transcript", () => ({
  YoutubeTranscript: {
    fetchTranscript: (...args: unknown[]) => fetchTranscriptMock(...args),
  },
}));

vi.mock("@/lib/youtube/metadata", async () => {
  const actual = await vi.importActual<typeof import("@/lib/youtube/metadata")>(
    "@/lib/youtube/metadata",
  );
  return {
    ...actual,
    fetchVideoMetadata: (...args: unknown[]) => fetchVideoMetadataMock(...args),
  };
});

const { fetchTranscriptForUrl } = await import("@/lib/youtube/fetch");

function networkError() {
  const error = new Error("fetch failed: getaddrinfo ENOTFOUND www.youtube.com");
  error.name = "TypeError";
  return error;
}

/** What `youtube-transcript` returns on its primary (milliseconds) path. */
const RAW_MS = [
  { text: "Hello and welcome", offset: 0, duration: 2200 },
  { text: "to the studio.", offset: 2200, duration: 1800 },
  { text: "Let's read a video.", offset: 4000, duration: 2000 },
];

beforeEach(() => {
  fetchTranscriptMock.mockReset();
  fetchVideoMetadataMock.mockReset();
  fetchVideoMetadataMock.mockResolvedValue({
    videoId: "dQw4w9WgXcQ",
    url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    title: "A real video",
    author: "A channel",
    thumbnailUrl: "https://i.ytimg.com/vi/dQw4w9WgXcQ/hqdefault.jpg",
    durationSeconds: 42,
    captionTracks: [
      { languageCode: "en", name: "English", kind: undefined },
      { languageCode: "en", name: "English (auto-generated)", kind: "asr" },
    ],
    hasOnlyAutoCaptions: false,
    resolvedBy: "innertube",
  });
  delete process.env.TRANSTUDIO_DEMO_MODE;
});

describe("fetchTranscriptForUrl — validation", () => {
  it("rejects input that isn't a YouTube link without touching the network", async () => {
    const result = await fetchTranscriptForUrl("https://vimeo.com/12345");
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.error).toBe("invalid-url");
    expect(fetchTranscriptMock).not.toHaveBeenCalled();
  });
});

describe("fetchTranscriptForUrl — happy path", () => {
  it("returns a normalised, seconds-based payload with metadata", async () => {
    fetchTranscriptMock.mockResolvedValue(RAW_MS);

    const result = await fetchTranscriptForUrl("https://www.youtube.com/watch?v=dQw4w9WgXcQ");
    expect(result.ok).toBe(true);
    if (!result.ok) return;

    // Milliseconds were converted to seconds (the normalizer's whole job).
    expect(result.transcript.segments[1].offset).toBe(2.2);
    expect(result.transcript.durationSeconds).toBeCloseTo(6, 5);
    // "Hello and welcome to the studio. Let's read a video." → 10 words
    expect(result.transcript.wordCount).toBe(10);
    expect(result.transcript.language).toBe("en");
    expect(result.transcript.isAutoGenerated).toBe(false);

    // Metadata is merged in for the player + export filenames.
    expect(result.metadata.title).toBe("A real video");
    expect(result.metadata.durationSeconds).toBe(42);
    expect(result.notice).toBeUndefined();
  });

  it("honours an explicit language request", async () => {
    fetchTranscriptMock.mockResolvedValue(RAW_MS);
    await fetchTranscriptForUrl("dQw4w9WgXcQ", { lang: "en" });
    expect(fetchTranscriptMock).toHaveBeenCalledWith(
      "dQw4w9WgXcQ",
      expect.objectContaining({ lang: "en" }),
    );
  });
});

describe("fetchTranscriptForUrl — environment failures", () => {
  it("falls back to the demo transcript when YouTube is unreachable", async () => {
    fetchTranscriptMock.mockRejectedValue(networkError());

    const result = await fetchTranscriptForUrl("https://youtu.be/dQw4w9WgXcQ");
    expect(result.ok).toBe(true);
    if (!result.ok) return;

    expect(result.transcript.source).toBe("demo");
    expect(result.transcript.segments.length).toBeGreaterThan(10);
    // The reason is surfaced so the UI can be honest about it.
    expect(result.notice).toMatch(/cannot reach youtube/i);
  });

  it("reports an error instead when the fallback is disabled", async () => {
    fetchTranscriptMock.mockRejectedValue(networkError());

    const result = await fetchTranscriptForUrl("https://youtu.be/dQw4w9WgXcQ", {
      allowDemoFallback: false,
    });
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.error).toBe("blocked");
  });
});

describe("fetchTranscriptForUrl — video problems are NOT masked", () => {
  it("surfaces disabled captions as a real error (no demo substitution)", async () => {
    const disabled = new Error("captions disabled");
    disabled.name = "YoutubeTranscriptDisabledError";
    fetchTranscriptMock.mockRejectedValue(disabled);

    const result = await fetchTranscriptForUrl("https://youtu.be/dQw4w9WgXcQ");
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.error).toBe("disabled");
    expect(result.hint).toBeTruthy();
  });

  it("surfaces an empty caption track", async () => {
    fetchTranscriptMock.mockResolvedValue([]);

    const result = await fetchTranscriptForUrl("https://youtu.be/dQw4w9WgXcQ");
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.error).toBe("empty");
  });

  it("surfaces a private/deleted video", async () => {
    const unavailable = new Error("unavailable");
    unavailable.name = "YoutubeTranscriptVideoUnavailableError";
    fetchTranscriptMock.mockRejectedValue(unavailable);

    const result = await fetchTranscriptForUrl("https://youtu.be/dQw4w9WgXcQ");
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.error).toBe("not-found");
  });
});

describe("fetchTranscriptForUrl — demo mode", () => {
  it("serves the demo transcript without any scraping when forced", async () => {
    process.env.TRANSTUDIO_DEMO_MODE = "1";
    const result = await fetchTranscriptForUrl("https://youtu.be/dQw4w9WgXcQ");

    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.transcript.source).toBe("demo");
    expect(fetchTranscriptMock).not.toHaveBeenCalled();
    delete process.env.TRANSTUDIO_DEMO_MODE;
  });
});
