/**
 * ─────────────────────────────────────────────────────────────────────────────
 *  The core engine — URL in, complete transcript payload out. SERVER ONLY.
 * ─────────────────────────────────────────────────────────────────────────────
 *  Ladder (first success wins):
 *    1. Our own multi-client caption fetcher (`captions.ts`) — understands every
 *       format YouTube serves, and works from datacenter IPs where the WEB
 *       client hides captions.
 *    2. `youtube-transcript` — kept as a second opinion; it uses a different
 *       code path and sometimes succeeds where we don't.
 *    3. Demo transcript — ONLY when the failure is environmental (bot wall,
 *       consent, rate limit, no network). Real problems (private, deleted,
 *       captions disabled) are reported as errors, never masked.
 *
 *  Every attempt records a diagnostic line, which travels with the result so
 *  the UI (and `/status`) can show exactly what happened.
 */
import { YoutubeTranscript } from "youtube-transcript";

import { GEMINI } from "@/lib/constants";
import type {
  FetchTranscriptResult,
  TranscriptPayload,
  TranscriptSource,
} from "@/lib/types";
import { parseYouTubeUrl } from "@/lib/utils";
import {
  fetchCaptionsDirect,
  describeDiagnostics,
  type Diagnostic,
} from "@/lib/youtube/captions";
import { proxiedFetcher } from "@/lib/youtube/clients";
import { buildDemoTranscript, DEMO_AUTHOR, DEMO_TITLE } from "@/lib/youtube/demo";
import { fetchVideoMetadata } from "@/lib/youtube/metadata";
import { normalizeSegments } from "@/lib/youtube/normalize";
import {
  classifyTranscriptError,
  type ClassifiedTranscriptError,
} from "@/lib/youtube/probe";

export interface FetchTranscriptOptions {
  /** Preferred caption language, e.g. "en". Falls back to what YouTube offers. */
  lang?: string;
  /** Budget per strategy. */
  timeoutMs?: number;
  /**
   * When the failure is environmental (this host cannot reach YouTube), return
   * the demo transcript instead of a hard failure.
   */
  allowDemoFallback?: boolean;
}

/* ─────────────────────────── scraper concurrency ─────────────────────────── */

const MAX_CONCURRENT_SCRAPES = 3;
let inFlight = 0;
const queue: Array<() => void> = [];

async function withScrapeSlot<T>(task: () => Promise<T>): Promise<T> {
  if (inFlight >= MAX_CONCURRENT_SCRAPES) {
    await new Promise<void>((resolve) => queue.push(resolve));
  }
  inFlight += 1;
  try {
    return await task();
  } finally {
    inFlight -= 1;
    queue.shift()?.();
  }
}

/** The library path uses the same proxy as our own fetcher, plus a timeout. */
function timedFetch(signal: AbortSignal): typeof fetch {
  const base = proxiedFetcher() ?? fetch;
  return ((input: RequestInfo | URL, init?: RequestInit) =>
    base(input, { ...init, signal })) as typeof fetch;
}

/* ────────────────────────────── result shapes ───────────────────────────── */

function demoResult(reason: string, diagnostics: Diagnostic[]): FetchTranscriptResult {
  const demo = buildDemoTranscript();
  const lines = describeDiagnostics(diagnostics);

  return {
    ok: true,
    transcript: demo,
    metadata: {
      videoId: demo.videoId,
      url: "",
      title: DEMO_TITLE,
      author: DEMO_AUTHOR,
      thumbnailUrl: "",
      durationSeconds: demo.durationSeconds,
    },
    notice:
      `${reason} This host cannot load YouTube captions right now, so a built-in demo ` +
      `transcript is shown instead — reading, seeking and exporting all still work.`,
    ...(lines.length > 0 ? { diagnostics: lines } : {}),
  };
}

function payloadFrom(args: {
  videoId: string;
  url: string;
  language: string;
  languageLabel: string;
  isAutoGenerated: boolean;
  source: TranscriptSource;
  strategy?: string;
  segments: TranscriptPayload["segments"];
  text: string;
  wordCount: number;
  characterCount: number;
  durationSeconds: number;
}): TranscriptPayload {
  const payload: TranscriptPayload = {
    videoId: args.videoId,
    url: args.url,
    language: args.language,
    languageLabel: args.languageLabel,
    isAutoGenerated: args.isAutoGenerated,
    source: args.source,
    segments: args.segments,
    text: args.text,
    wordCount: args.wordCount,
    characterCount: args.characterCount,
    durationSeconds: args.durationSeconds,
    fetchedAt: new Date().toISOString(),
  };
  if (args.strategy) payload.strategy = args.strategy;
  return payload;
}

/* ─────────────────────────────── entry point ────────────────────────────── */

/**
 * Fetch a full transcript for a video URL or id.
 * Never throws — every outcome is a typed result.
 */
export async function fetchTranscriptForUrl(
  input: string,
  options: FetchTranscriptOptions = {},
): Promise<FetchTranscriptResult> {
  const perStrategyTimeout = options.timeoutMs ?? 9_000;
  const allowDemoFallback = options.allowDemoFallback ?? true;

  // ── 1. Validate ──────────────────────────────────────────────────────────
  const parsed = parseYouTubeUrl(input);
  if (!parsed) {
    return {
      ok: false,
      error: "invalid-url",
      message: "That doesn't look like a YouTube link.",
      hint: "Paste a watch URL, a youtu.be short link, or an 11-character video id.",
    };
  }

  if (process.env.TRANSTUDIO_DEMO_MODE === "1") {
    return demoResult("TRANSTUDIO_DEMO_MODE is enabled.", []);
  }

  const diagnostics: Diagnostic[] = [];

  /* ── 2. Primary: our own multi-client fetcher ─────────────────────────── */
  try {
    const direct = await fetchCaptionsDirect(parsed.videoId, {
      ...(options.lang ? { lang: options.lang } : {}),
      timeoutMs: perStrategyTimeout,
      ...(proxiedFetcher() ? { fetcher: proxiedFetcher() } : {}),
    });
    diagnostics.push(...direct.diagnostics);

    if (direct.ok) {
      // The player response usually carries title/author/duration, so we only
      // make an extra metadata call when something is missing.
      let title = direct.title ?? "";
      let author = direct.author ?? "";
      let durationSeconds = direct.durationSeconds ?? 0;
      let thumbnailUrl = `https://i.ytimg.com/vi/${parsed.videoId}/hqdefault.jpg`;

      if (!title) {
        const metadata = await fetchVideoMetadata(parsed.videoId, {
          timeoutMs: 6_000,
        }).catch(() => null);
        if (metadata) {
          title = metadata.title;
          author = author || metadata.author;
          durationSeconds = durationSeconds || metadata.durationSeconds;
          thumbnailUrl = metadata.thumbnailUrl || thumbnailUrl;
        }
      }

      const text = direct.segments.map((segment) => segment.text).join(" ");
      const transcript = payloadFrom({
        videoId: parsed.videoId,
        url: `https://www.youtube.com/watch?v=${parsed.videoId}`,
        language: direct.language,
        languageLabel: direct.languageLabel,
        isAutoGenerated: direct.isAutoGenerated,
        source: "youtube-transcript",
        strategy: direct.strategy,
        segments: direct.segments,
        text,
        wordCount: text ? text.split(/\s+/).length : 0,
        characterCount: text.length,
        durationSeconds: direct.segments.at(-1)?.end ?? 0,
      });

      warnIfTooLong(transcript);

      return {
        ok: true,
        transcript,
        metadata: {
          videoId: parsed.videoId,
          url: transcript.url,
          title,
          author,
          thumbnailUrl,
          durationSeconds: durationSeconds || transcript.durationSeconds,
          ...(parsed.startAt ? { startAt: parsed.startAt } : {}),
        },
        diagnostics: describeDiagnostics(diagnostics),
      };
    }
  } catch (error) {
    diagnostics.push({
      strategy: "direct",
      ok: false,
      detail: error instanceof Error ? error.message : "unexpected error",
    });
  }

  /* ── 3. Secondary: the youtube-transcript library ─────────────────────── */
  const library = await tryLibrary(parsed.videoId, options, diagnostics);
  if (library.kind === "ok") {
    warnIfTooLong(library.payload);
    const metadata = await fetchVideoMetadata(parsed.videoId, {
      timeoutMs: 6_000,
    }).catch(() => null);

    return {
      ok: true,
      transcript: library.payload,
      metadata: {
        videoId: parsed.videoId,
        url: library.payload.url,
        title: metadata?.title ?? "",
        author: metadata?.author ?? "",
        thumbnailUrl:
          metadata?.thumbnailUrl ?? `https://i.ytimg.com/vi/${parsed.videoId}/hqdefault.jpg`,
        durationSeconds: metadata?.durationSeconds || library.payload.durationSeconds,
        ...(parsed.startAt ? { startAt: parsed.startAt } : {}),
      },
      diagnostics: describeDiagnostics(diagnostics),
    };
  }

  /* ── 4. Give up — but say exactly why ────────────────────────────────── */
  const environmental = isEnvironmental(diagnostics);
  if (environmental && allowDemoFallback) {
    return demoResult("YouTube blocked caption requests from this server.", diagnostics);
  }

  const verdict = diagnostics.find((entry) =>
    /unavailable|private|age-restricted|not playable/i.test(entry.detail),
  );

  // Prefer the library's precise verdict when it has one: "captions disabled"
  // and "video unavailable" deserve their own message, not a generic failure.
  const specific = library.classified;
  const useSpecific = specific && specific.code !== "unknown" && !environmental;

  return {
    ok: false,
    error: useSpecific
      ? specific.code
      : verdict
        ? "not-found"
        : environmental
          ? "blocked"
          : "empty",
    message: useSpecific
      ? specific.message
      : verdict
        ? "YouTube says this video can't be played here."
        : environmental
          ? "This server couldn't reach YouTube's caption service."
          : "No captions could be read for this video.",
    hint: useSpecific
      ? specific.hint
      : environmental
        ? "Datacenter IPs are often challenged by YouTube. Set TRANSCRIPT_PROXY_URL, deploy somewhere with a normal egress, or try again in a minute."
        : "The video may have captions disabled, or only auto-captions that YouTube hasn't generated yet. Try another video, or load the demo transcript.",
    videoId: parsed.videoId,
    diagnostics: describeDiagnostics(diagnostics),
  };
}

/* ───────────────────────────── library path ─────────────────────────────── */

type LibraryAttempt =
  | { kind: "ok"; payload: TranscriptPayload }
  | { kind: "error"; classified?: ClassifiedTranscriptError };

async function tryLibrary(
  videoId: string,
  options: FetchTranscriptOptions,
  diagnostics: Diagnostic[],
): Promise<LibraryAttempt> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), (options.timeoutMs ?? 9_000) * 2);

  try {
    const raw = await withScrapeSlot(() =>
      YoutubeTranscript.fetchTranscript(videoId, {
        ...(options.lang ? { lang: options.lang } : {}),
        fetch: timedFetch(controller.signal),
      }),
    );

    const normalized = normalizeSegments(raw ?? []);
    if (normalized.segments.length === 0) {
      diagnostics.push({
        strategy: "youtube-transcript",
        ok: false,
        detail: `returned ${raw?.length ?? 0} rows, none usable`,
      });
      return { kind: "error" };
    }

    diagnostics.push({
      strategy: "youtube-transcript",
      ok: true,
      detail: `${normalized.unit} detected, ${normalized.segments.length} lines`,
    });

    return {
      kind: "ok",
      payload: payloadFrom({
        videoId,
        url: `https://www.youtube.com/watch?v=${videoId}`,
        language: raw?.[0]?.lang ?? "en",
        languageLabel: raw?.[0]?.lang ?? "en",
        isAutoGenerated: false,
        source: "youtube-transcript",
        strategy: "youtube-transcript",
        segments: normalized.segments,
        text: normalized.text,
        wordCount: normalized.wordCount,
        characterCount: normalized.characterCount,
        durationSeconds: normalized.durationSeconds,
      }),
    };
  } catch (error) {
    const classified = classifyTranscriptError(error);
    diagnostics.push({
      strategy: "youtube-transcript",
      ok: false,
      detail: `${classified.code}: ${classified.message}`,
    });
    return { kind: "error", classified };
  } finally {
    clearTimeout(timer);
  }
}

/* ─────────────────────────────── helpers ───────────────────────────────── */

function isEnvironmental(diagnostics: Diagnostic[]): boolean {
  if (diagnostics.length === 0) return true;
  const signals = [
    "not a bot",
    "sign in",
    "login_required",
    "consent",
    "too many",
    "rate limit",
    "429",
    "blocked",
    "enotfound",
    "fetch failed",
    "network",
    "http 5",
    "0 caption tracks",
    "captions not exposed",
  ];
  return diagnostics.every((entry) =>
    entry.ok ? true : signals.some((signal) => entry.detail.toLowerCase().includes(signal)),
  );
}

function warnIfTooLong(transcript: TranscriptPayload) {
  if (transcript.characterCount > GEMINI.maxContextCharacters) {
    console.warn(
      `[transtudio] transcript is ${transcript.characterCount} chars (limit ${GEMINI.maxContextCharacters}) — the AI context will be chunked in Step 4.`,
    );
  }
}
