/**
 * Step 4 + 5 wiring checks — opt-in (see vitest.verify.config.ts).
 *
 * These checks deliberately stay network-free. They drive the real stores and
 * small controls through the seams that matter in a browser: framed streams,
 * clip arming, and the six export choices.
 */
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { act } from "react";
import { createRoot, type Root } from "react-dom/client";

import { ClipActions } from "@/components/workspace/ClipActions";
import { ExportMenu } from "@/components/export/ExportMenu";
import { EXPORT_PRESETS, clipColorAt } from "@/lib/constants";
import { buildTranscriptContext } from "@/lib/gemini/prompts";
import { mapClipPlan, buildClipOverlay } from "@/lib/clips/map";
import { parseClipPlan } from "@/lib/clips/parse";
import { buildCsv, buildExport, buildSrt, buildVtt, mergeIntoParagraphs } from "@/lib/export/formats";
import type { ClipPlan, TranscriptPayload, ViralClip } from "@/lib/types";
import { useChatStore } from "@/stores/useChatStore";
import { usePlaybackStore } from "@/stores/usePlaybackStore";
import { useSettingsStore } from "@/stores/useSettingsStore";
import { useTranscriptStore } from "@/stores/useTranscriptStore";

const segments = [
  { id: 0, text: "The opening thought is long enough to quote.", offset: 0, duration: 4, end: 4, charCount: 44 },
  { id: 1, text: "The second thought makes the point land.", offset: 4, duration: 4, end: 8, charCount: 40 },
  { id: 2, text: "A closing thought follows.", offset: 8, duration: 4, end: 12, charCount: 25 },
];

const transcript: TranscriptPayload = {
  videoId: "verify-video",
  title: "Verification video",
  url: "https://youtube.com/watch?v=verify-video",
  language: "en",
  languageLabel: "English",
  isAutoGenerated: false,
  source: "demo",
  segments,
  text: segments.map((segment) => segment.text).join(" "),
  wordCount: 21,
  characterCount: 115,
  durationSeconds: 12,
  fetchedAt: "2026-09-26T00:00:00.000Z",
};

const rawPlan = (clips = [{ title: "Opening", start_time: 0, end_time: 8, transcript_text: "model quote", viral_score: 88 }]): ClipPlan => ({ clips });

function makeClip(): ViralClip {
  return {
    ...rawPlan().clips[0],
    id: "clip-1",
    index: 0,
    color: clipColorAt(0),
    start: 0,
    end: 8,
    hookType: "hook",
    segmentIds: [0, 1],
    segmentStartIndex: 0,
    segmentEndIndex: 2,
    transcript_text: "The opening thought is long enough to quote. The second thought makes the point land.",
  };
}

let host: HTMLDivElement;
let root: Root;

beforeEach(() => {
  (globalThis as unknown as { IS_REACT_ACT_ENVIRONMENT: boolean }).IS_REACT_ACT_ENVIRONMENT = true;
  host = document.createElement("div");
  document.body.appendChild(host);
  root = createRoot(host);
  useTranscriptStore.setState({ transcript, status: "success", metadata: { videoId: transcript.videoId, title: transcript.title, url: transcript.url, thumbnailUrl: "" }, clips: [] });
  usePlaybackStore.setState({ loopRange: null, controller: null, status: "unstarted", currentTime: 0, activeSegmentIndex: -1 });
  useSettingsStore.setState({ viewMode: "split", sidebarOpen: false });
  useChatStore.setState({ messages: [], isStreaming: false, mode: "chat" });
});

afterEach(() => {
  vi.unstubAllGlobals();
  act(() => root.unmount());
  host.remove();
});

describe("Step 5 clip data", () => {
  it("extracts a plan from a fenced model answer", () => {
    expect(parseClipPlan('```json\n{"clips":[{"title":"A","start_time":0,"end_time":4,"transcript_text":"words","viral_score":90}]}\n```').clips).toHaveLength(1);
  });
  it("repairs millisecond ranges", () => {
    const result = mapClipPlan(rawPlan([{ title: "A", start_time: 2_000, end_time: 8_000, transcript_text: "x", viral_score: 50 }]), transcript);
    expect(result[0].repaired).toBe(true);
  });
  it("snaps a range to complete caption lines", () => {
    const result = mapClipPlan(rawPlan(), transcript);
    expect(result[0].start).toBe(0);
    expect(result[0].end).toBe(8);
    expect(result[0].segmentIds).toEqual([0, 1]);
  });
  it("drops a range outside the spoken transcript", () => {
    expect(mapClipPlan(rawPlan([{ title: "bad", start_time: 90, end_time: 100, transcript_text: "x", viral_score: 1 }]), transcript)).toEqual([]);
  });
  it("assigns colours in plan order before sorting", () => {
    const result = mapClipPlan(rawPlan([
      { title: "late", start_time: 8, end_time: 12, transcript_text: "x", viral_score: 1 },
      { title: "early", start_time: 0, end_time: 4, transcript_text: "x", viral_score: 2 },
    ]), transcript);
    expect(result[0].title).toBe("early");
    expect(result[0].color.id).toBe("red");
  });
  it("builds a segment overlay for overlapping clips", () => {
    const overlay = buildClipOverlay([makeClip()]);
    expect(overlay.bySegment.get(1)?.[0].id).toBe("clip-1");
  });
  it("keeps the model quote out of the canonical mapped text", () => {
    expect(mapClipPlan(rawPlan(), transcript)[0].transcript_text).toContain("opening thought");
  });

  it("arms a clip before a player exists", () => {
    usePlaybackStore.getState().playClip({ start: 0, end: 8, clipId: "clip-1" });
    expect(usePlaybackStore.getState().loopRange?.clipId).toBe("clip-1");
  });
  it("clears an armed loop", () => {
    usePlaybackStore.getState().playClip({ start: 0, end: 8, clipId: "clip-1" });
    usePlaybackStore.getState().clearClip();
    expect(usePlaybackStore.getState().loopRange).toBeNull();
  });
  it("renders armed-but-paused as Stop rather than Play", async () => {
    const clip = makeClip();
    await act(async () => root.render(<ClipActions clip={clip} />));
    await act(async () => usePlaybackStore.getState().playClip({ start: 0, end: 8, clipId: clip.id }));
    expect(host.querySelector("[data-armed=\"true\"]")).not.toBeNull();
    expect(host.querySelector("[aria-label^=\"Stop\"]")).not.toBeNull();
    expect(host.querySelector("[data-playing=\"false\"]")).not.toBeNull();
  });
});

describe("Step 5 exports", () => {
  it("offers all six formats", () => {
    expect(EXPORT_PRESETS.map((preset) => preset.id)).toEqual(["txt", "md", "srt", "vtt", "json", "csv"]);
  });
  it("builds SubRip and WebVTT timecodes", () => {
    expect(buildSrt(transcript)).toContain("00:00:00,000 --> 00:00:04,000");
    expect(buildVtt(transcript)).toContain("00:00:00.000 --> 00:00:04.000");
  });
  it("quotes a CSV cell containing punctuation", () => {
    expect(buildCsv({ ...transcript, segments: [{ ...segments[0], text: "comma, line" }] })).toContain('"comma, line"');
  });
  it("uses the TranStudio untitled filename", () => {
    expect(buildExport({ ...transcript, title: undefined }, [], { format: "txt", includeTimestamps: false, includeHeader: true }).filename).toBe("transtudio-verify-video.txt");
  });
  it("merges subtitle-sized cues into one readable paragraph", () => {
    expect(mergeIntoParagraphs(segments)).toHaveLength(1);
  });
  it("opens the live export preview", async () => {
    await act(async () => root.render(<ExportMenu />));
    await act(async () => host.querySelector("button")?.dispatchEvent(new MouseEvent("click", { bubbles: true })));
    expect(host.querySelectorAll('[role="menuitem"]')).toHaveLength(6);
    expect(host.textContent).toContain("Download");
  });
});

describe("Step 4 assistant context and stream", () => {
  it("prefers flat text for chat context", () => {
    expect(buildTranscriptContext({ videoId: "v", title: "", durationSeconds: 1, text: "flat source", segments: [{ i: 0, t: 0, d: 1, x: "other" }], language: "en" })).toContain("flat source");
  });
  it("uses timed records for clip context", () => {
    expect(buildTranscriptContext({ videoId: "v", title: "", durationSeconds: 1, text: "", segments: [{ i: 0, t: 0, d: 1, x: "timed" }], language: "en" }, "clips")).toContain("#0");
  });
  it("trims context and marks the omission", () => {
    expect(buildTranscriptContext({ videoId: "v", title: "", durationSeconds: 1, text: "one two three four five six seven eight nine", segments: [], language: "en" }, "chat", 30)).toContain("Context note");
  });
  it("does not send the current question twice", async () => {
    useChatStore.setState({ messages: [{ id: "old", role: "user", content: "old question", createdAt: 1, status: "done" }] });
    let requestBody: { history: Array<{ role: string; content: string }> } | undefined;
    vi.stubGlobal("fetch", vi.fn(async (_url: string, init: RequestInit) => {
      requestBody = JSON.parse(String(init.body));
      const stream = new ReadableStream({ start(controller) { controller.enqueue(new TextEncoder().encode('{"type":"delta","text":"ok"}\n{"type":"done"}\n')); controller.close(); } });
      return new Response(stream, { status: 200 });
    }));
    await useChatStore.getState().sendMessage("new question");
    expect(requestBody?.history.map((entry) => entry.content)).toEqual(["old question"]);
    expect(requestBody?.history).not.toContainEqual({ role: "user", content: "new question" });
  });
  it("buffers a frame split across network chunks", async () => {
    vi.stubGlobal("fetch", vi.fn(async () => {
      const stream = new ReadableStream({ start(controller) { const encoder = new TextEncoder(); controller.enqueue(encoder.encode('{"type":"delta","text":"hel')); controller.enqueue(encoder.encode('lo"}\n{"type":"done"}\n')); controller.close(); } });
      return new Response(stream, { status: 200 });
    }));
    await useChatStore.getState().sendMessage("hello");
    expect(useChatStore.getState().messages.at(-1)?.content).toBe("hello");
  });
  it("maps a clip event into the transcript store", async () => {
    vi.stubGlobal("fetch", vi.fn(async () => {
      const event = JSON.stringify({ type: "clips", plan: rawPlan() });
      const stream = new ReadableStream({ start(controller) { controller.enqueue(new TextEncoder().encode(`${event}\n{"type":"done"}\n`)); controller.close(); } });
      return new Response(stream, { status: 200 });
    }));
    await useChatStore.getState().sendMessage("find clips", "clips");
    expect(useTranscriptStore.getState().clips).toHaveLength(1);
  });
  it("keeps an assistant error visible after done", async () => {
    vi.stubGlobal("fetch", vi.fn(async () => {
      const stream = new ReadableStream({ start(controller) { controller.enqueue(new TextEncoder().encode('{"type":"error","code":"missing-key","message":"Set up Gemini first."}\n{"type":"done"}\n')); controller.close(); } });
      return new Response(stream, { status: 200 });
    }));
    await useChatStore.getState().sendMessage("question");
    expect(useChatStore.getState().messages.at(-1)?.status).toBe("error");
    expect(useChatStore.getState().messages.at(-1)?.error).toContain("Set up");
  });
  it("marks a stream complete exactly once", async () => {
    vi.stubGlobal("fetch", vi.fn(async () => new Response('{"type":"done"}\n')));
    await useChatStore.getState().sendMessage("question");
    expect(useChatStore.getState().isStreaming).toBe(false);
    expect(useChatStore.getState().messages.filter((message) => message.role === "assistant")).toHaveLength(1);
  });
  it("renders the assistant shell only when opened", async () => {
    // The header owns the open flag; this check verifies the preference seam.
    expect(useSettingsStore.getState().sidebarOpen).toBe(false);
    useSettingsStore.getState().setSidebarOpen(true);
    expect(useSettingsStore.getState().sidebarOpen).toBe(true);
  });
});
