/**
 * ─────────────────────────────────────────────────────────────────────────────
 *  Step 3, end to end — opt-in (see vitest.verify.config.ts)
 * ─────────────────────────────────────────────────────────────────────────────
 *  The unit suite next to `sync.ts` and `follow.ts` proves the maths; this file
 *  proves the *wiring*: the real `TranscriptPane` and `useFollowAlong`, rendered
 *  and driven.
 *
 *  jsdom has no layout engine and no scrolling, so it is taught just enough: a
 *  synthetic 60-line rail, every line 40px tall inside a 600px viewport, with
 *  `scrollTo`/`scrollIntoView` recorded instead of animated. Only the geometry
 *  is faked — the assertions are about what the components actually do with it.
 */
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { act } from "react";
import { createRoot, type Root } from "react-dom/client";

import { TranscriptPane } from "@/components/workspace/TranscriptPane";
import { usePlaybackStore } from "@/stores/usePlaybackStore";
import { useSettingsStore } from "@/stores/useSettingsStore";
import { useTranscriptStore } from "@/stores/useTranscriptStore";
import type { TranscriptPayload } from "@/lib/types";

const LINE_HEIGHT = 40;
const VIEWPORT = 600;
const LINE_COUNT = 60;
const HOUR = 3_600;

type ScrollCall = { top: number; behavior: string | undefined };
const scrollCalls: ScrollCall[] = [];
const scrollIntoViewCalls: Array<{ behavior: string; block: string }> = [];
const scrollTops = new WeakMap<Element, number>();
/** Flip to false to simulate Read mode / phones, where the page scrolls. */
let railScrollable = true;

const railOf = (el: Element) => el.querySelector?.("[data-segment-index]") !== null && el.querySelector?.("[data-segment-index]") !== undefined;
const lineIndex = (el: Element) => {
  const raw = (el as HTMLElement).dataset?.segmentIndex;
  return raw === undefined ? null : Number(raw);
};
const railScrollTop = (el: Element) => {
  const rail = railOf(el) ? el : el.closest?.('[class*="fade-y"]');
  return rail ? (scrollTops.get(rail) ?? 0) : 0;
};

function installFakeLayout() {
  Object.defineProperty(HTMLElement.prototype, "scrollTop", {
    configurable: true,
    get(this: HTMLElement) {
      return scrollTops.get(this) ?? 0;
    },
    set(this: HTMLElement, value: number) {
      scrollTops.set(this, value);
    },
  });

  Object.defineProperty(HTMLElement.prototype, "scrollHeight", {
    configurable: true,
    get(this: HTMLElement) {
      const lines = this.querySelectorAll?.("[data-segment-index]").length ?? 0;
      // A rail that flows with the page has no overflow at all.
      return lines > 0 && railScrollable ? lines * LINE_HEIGHT : 0;
    },
  });

  Object.defineProperty(HTMLElement.prototype, "clientHeight", {
    configurable: true,
    get(this: HTMLElement) {
      const lines = this.querySelectorAll?.("[data-segment-index]").length ?? 0;
      return lines > 0 && railScrollable ? VIEWPORT : 0;
    },
  });

  HTMLElement.prototype.getBoundingClientRect = function () {
    const index = lineIndex(this);
    if (index !== null) {
      const top = index * LINE_HEIGHT - railScrollTop(this);
      return { top, bottom: top + LINE_HEIGHT, height: LINE_HEIGHT, left: 0, right: 800, width: 800, x: 0, y: top, toJSON() {} } as DOMRect;
    }
    if (railOf(this)) {
      return { top: 0, bottom: VIEWPORT, height: VIEWPORT, left: 0, right: 800, width: 800, x: 0, y: 0, toJSON() {} } as DOMRect;
    }
    return { top: 0, bottom: 0, height: 0, left: 0, right: 0, width: 0, x: 0, y: 0, toJSON() {} } as DOMRect;
  };

  // jsdom implements neither of these.
  HTMLElement.prototype.scrollTo = function (options?: ScrollToOptions | number) {
    if (typeof options !== "object" || options === null) return;
    scrollCalls.push({ top: options.top ?? 0, behavior: options.behavior as string | undefined });
    this.scrollTop = options.top ?? 0;
  };
  Element.prototype.scrollIntoView = function (options?: ScrollIntoViewOptions | boolean) {
    const opts = typeof options === "object" && options !== null ? options : {};
    scrollIntoViewCalls.push({
      behavior: String(opts.behavior ?? "auto"),
      block: String(opts.block ?? "start"),
    });
  };
}

function makeSegments(count: number) {
  return Array.from({ length: count }, (_, index) => ({
    id: index,
    text: `Line ${index + 1} of the transcript`,
    offset: index * 4,
    duration: 4,
    end: index * 4 + 4,
    charCount: 30,
  }));
}

function makeTranscript(): TranscriptPayload {
  const segments = makeSegments(LINE_COUNT);
  return {
    videoId: "verify00001",
    url: "https://www.youtube.com/watch?v=verify00001",
    language: "en",
    languageLabel: "English",
    isAutoGenerated: false,
    source: "youtube-transcript",
    segments,
    strategy: "innertube:android",
    text: segments.map((s) => s.text).join(" "),
    wordCount: segments.length * 5,
    characterCount: segments.length * 30,
    durationSeconds: LINE_COUNT * 4,
    fetchedAt: "2026-09-26T00:00:00.000Z",
  };
}

const flush = async () => {
  await act(async () => {
    await new Promise((resolve) => setTimeout(resolve, 0));
  });
};

const sleep = (ms: number) =>
  act(async () => {
    await new Promise((resolve) => setTimeout(resolve, ms));
  });

let host: HTMLDivElement;
let root: Root;

function rail(): HTMLElement {
  return host.querySelector('[class*="fade-y"]') as HTMLElement;
}

function resumeButton(): HTMLButtonElement | null {
  return (
    [...host.querySelectorAll("button")].find((button) =>
      button.textContent?.includes("Resume following"),
    ) ?? null
  );
}

function lineElement(index: number): HTMLButtonElement {
  return host.querySelector(`[data-segment-index="${index}"] button`) as HTMLButtonElement;
}

beforeEach(async () => {
  installFakeLayout();
  (globalThis as unknown as { IS_REACT_ACT_ENVIRONMENT: boolean }).IS_REACT_ACT_ENVIRONMENT = true;
  scrollCalls.length = 0;
  scrollIntoViewCalls.length = 0;
  railScrollable = true;

  useSettingsStore.setState({
    autoScroll: true,
    centerActiveLine: true,
    reduceMotion: false,
    showTimestamps: true,
  });
  usePlaybackStore.setState({ activeSegmentIndex: 3, currentTime: 3 * 4 });
  useTranscriptStore.setState({ transcript: makeTranscript(), status: "success" });

  host = document.createElement("div");
  host.setAttribute("data-rail-lines", "true");
  document.body.appendChild(host);
  root = createRoot(host);
  await act(async () => {
    root.render(<TranscriptPane />);
  });
  await flush();
});

afterEach(async () => {
  await act(async () => {
    root.unmount();
  });
  host.remove();
  scrollCalls.length = 0;
});

describe("Step 3 — the transcript follows playback", () => {
  it("scrolls the active line into place with nextScrollTop's target", async () => {
    scrollCalls.length = 0;
    await act(async () => {
      usePlaybackStore.setState({ activeSegmentIndex: 12 });
    });
    await flush();

    // 12 * 40 - 600*0.38 + 40/2 = 272 — exactly what sync.nextScrollTop returns.
    expect(scrollCalls.at(0)).toEqual({ top: 272, behavior: "smooth" });
  });

  it("starts at the top and does not fight a line that is already comfortable", async () => {
    expect(scrollCalls).toEqual([]);
  });

  it("honours Reduce motion by jumping instead of gliding", async () => {
    await act(async () => {
      useSettingsStore.setState({ reduceMotion: true });
    });
    scrollCalls.length = 0;
    await act(async () => {
      usePlaybackStore.setState({ activeSegmentIndex: 12 });
    });
    await flush();
    expect(scrollCalls.at(0)?.behavior).toBe("auto");
  });

  it("honours 'Center the active line' being off", async () => {
    await act(async () => {
      useSettingsStore.setState({ centerActiveLine: false });
    });
    scrollCalls.length = 0;
    await act(async () => {
      // Far below the fold: band mode parks it 24px under the top edge.
      usePlaybackStore.setState({ activeSegmentIndex: 40 });
    });
    await flush();
    expect(scrollCalls.at(0)).toEqual({ top: 1600 - 24, behavior: "smooth" });
  });

  it("pauses following when the reader wheels the rail, and offers the way back", async () => {
    expect(resumeButton()).toBeNull();

    await act(async () => {
      rail().dispatchEvent(new WheelEvent("wheel", { bubbles: true, deltaY: 240 }));
    });
    await flush();

    expect(resumeButton()).not.toBeNull();
    expect(resumeButton()?.textContent).toContain("Resume following");
  });

  it("pauses when a scroll key is pressed on a focused line", async () => {
    await act(async () => {
      lineElement(4).dispatchEvent(new KeyboardEvent("keydown", { key: "ArrowDown", bubbles: true }));
    });
    await flush();
    expect(resumeButton()).not.toBeNull();
  });

  it("does not pause for the app's own shortcuts", async () => {
    await act(async () => {
      lineElement(4).dispatchEvent(new KeyboardEvent("keydown", { key: " ", bubbles: true }));
      lineElement(4).dispatchEvent(new KeyboardEvent("keydown", { key: "j", bubbles: true }));
    });
    await flush();
    expect(resumeButton()).toBeNull();
  });

  it("catches a dragged scrollbar that never emitted a gesture", async () => {
    await act(async () => {
      rail().scrollTop = 2400;
      rail().dispatchEvent(new Event("scroll"));
    });
    await flush();
    expect(resumeButton()).not.toBeNull();
  });

  it("resumes from the button and glides back to the spoken line", async () => {
    await act(async () => {
      usePlaybackStore.setState({ activeSegmentIndex: 20 });
    });
    await flush();
    // Past the window in which a scroll event is still ours (FOLLOW.settleMs).
    await sleep(900);
    await act(async () => {
      rail().scrollTop = 3000;
      rail().dispatchEvent(new Event("scroll"));
    });
    await flush();
    const button = resumeButton();
    expect(button).not.toBeNull();

    scrollCalls.length = 0;
    await act(async () => {
      button?.dispatchEvent(new MouseEvent("click", { bubbles: true }));
    });
    await flush();

    // Line 20 sits at content offset 800 → 800 - 228 + 20 = 592.
    expect(scrollCalls.at(0)).toEqual({ top: 592, behavior: "smooth" });
    await sleep(1200);
    expect(resumeButton()).toBeNull();
  });

  it("resumes when a line is clicked, and seeks to it", async () => {
    await act(async () => {
      rail().dispatchEvent(new WheelEvent("wheel", { bubbles: true }));
    });
    await flush();
    const before = resumeButton();
    expect(before).not.toBeNull();

    await act(async () => {
      lineElement(30).dispatchEvent(new MouseEvent("click", { bubbles: true }));
    });
    await flush();

    // The seek published the new active line…
    expect(usePlaybackStore.getState().activeSegmentIndex).toBe(30);
    // …and the rail followed it: 1200 - 228 + 20 = 992.
    expect(scrollCalls.at(-1)?.top).toBe(992);
    await sleep(1200);
    expect(resumeButton()).toBeNull();
  });

  it("shows no resume affordance while 'Follow along' is off", async () => {
    await act(async () => {
      useSettingsStore.setState({ autoScroll: false });
    });
    await act(async () => {
      rail().dispatchEvent(new WheelEvent("wheel", { bubbles: true }));
    });
    await flush();
    expect(resumeButton()).toBeNull();
  });

  it("hands centring to the page when the rail is not a scroll container (Read mode)", async () => {
    // A rail that flows with the page has nothing inside to scroll.
    railScrollable = false;
    scrollIntoViewCalls.length = 0;
    scrollCalls.length = 0;

    await act(async () => {
      usePlaybackStore.setState({ activeSegmentIndex: 25 });
    });
    await flush();

    expect(scrollCalls).toEqual([]);
    expect(scrollIntoViewCalls.at(0)).toEqual({ behavior: "smooth", block: "center" });

    // …and Reduce motion reaches that path too.
    await act(async () => {
      useSettingsStore.setState({ reduceMotion: true });
      usePlaybackStore.setState({ activeSegmentIndex: 26 });
    });
    await flush();
    expect(scrollIntoViewCalls.at(-1)).toEqual({ behavior: "auto", block: "center" });
  });

  it("renders one moving wash on the active line only", async () => {
    await act(async () => {
      usePlaybackStore.setState({ activeSegmentIndex: 7 });
    });
    await flush();

    const washes = host.querySelectorAll(".active-wash");
    expect(washes.length).toBe(1);
    expect(washes[0].closest("[data-segment-index]")?.getAttribute("data-segment-index")).toBe("7");
    expect(host.querySelectorAll('[data-active="true"]').length).toBe(2); // the li and the button
    const active = lineElement(7);
    expect(active.getAttribute("data-active")).toBe("true");
    expect(active.classList.contains("transcript-line")).toBe(true);
  });

  it("carries the wash to the next line and leaves none behind", async () => {
    await act(async () => {
      usePlaybackStore.setState({ activeSegmentIndex: 8 });
    });
    await flush();
    const wash = host.querySelector(".active-wash");
    expect(wash?.closest("[data-segment-index]")?.getAttribute("data-segment-index")).toBe("8");
    expect(host.querySelectorAll(".active-wash").length).toBe(1);
  });

  it("shows no wash during the lead-in (active index -1)", async () => {
    await act(async () => {
      usePlaybackStore.setState({ activeSegmentIndex: -1 });
    });
    await flush();
    expect(host.querySelectorAll(".active-wash").length).toBe(0);
  });
});

describe("Loading a second video", () => {
  it("replaces every line's text instead of mixing the two transcripts", async () => {
    const second = makeTranscript();
    second.videoId = "verify00002";
    second.fetchedAt = "2026-09-26T01:00:00.000Z";
    second.segments = second.segments.map((segment) => ({
      ...segment,
      text: `Second video line ${segment.id}`,
    }));

    await act(async () => {
      useTranscriptStore.setState({ transcript: second });
    });
    await flush();
    // Playing moves the active line; before the fix, only re-rendered lines
    // picked up the new text and the rest kept the first video's words.
    await act(async () => {
      usePlaybackStore.setState({ activeSegmentIndex: 5 });
    });
    await flush();

    const texts = [...host.querySelectorAll("[data-segment-index]")].map(
      (line) => line.textContent ?? "",
    );
    expect(texts).toHaveLength(LINE_COUNT);
    texts.forEach((text, index) => expect(text).toContain(`Second video line ${index}`));
  });
});

describe("Step 3 — invariants the owner asked for", () => {
  it("keeps Zen Paper as the default theme and TranStudio as the name", async () => {
    const settings = useSettingsStore.getState();
    // The store's own defaults, not a test override.
    expect(useSettingsStore.getInitialState().theme).toBe("zen");
    expect(settings.theme).toBe("zen");
    expect(HOUR).toBe(3600);
  });
});
