"use client";

/**
 * Transcript store — owns the fetch lifecycle and the parsed transcript.
 * Deliberately UI-free: components subscribe, the server action stays the only
 * thing that knows how scraping works.
 */
import { create } from "zustand";

import type {
  AsyncStatus,
  FetchTranscriptResult,
  TranscriptErrorCode,
  TranscriptPayload,
  VideoMetadata,
  ViralClip,
} from "@/lib/types";
import { extractTranscriptAction, loadDemoTranscriptAction } from "@/app/actions/transcript";
import { describePasteFormat, parsePastedTranscript } from "@/lib/transcript/paste";
import { fetchCaptionsInBrowser } from "@/lib/transcript/browser-captions";
import { countWords, parseYouTubeUrl } from "@/lib/utils";

export interface TranscriptError {
  code: TranscriptErrorCode;
  message: string;
  hint?: string;
  /** Per-strategy attempt log — shown behind a "technical details" toggle. */
  diagnostics?: string[];
}

interface TranscriptState {
  status: AsyncStatus;
  /** The URL currently loaded or attempted (for the address bar + retry). */
  input: string;
  transcript: TranscriptPayload | null;
  metadata: VideoMetadata | null;
  /** Verified clip ranges produced for the current transcript. */
  clips: ViralClip[];
  error: TranscriptError | null;
  /** Set when the server had to substitute the demo transcript. */
  notice: string | null;
  /** Attempt log for the loaded transcript (success or failure). */
  diagnostics: string[];
  /** Non-blocking metadata warnings surfaced under the player. */
  lastFetchedAt: number | null;
  /** Paste dialog visibility. Held in the store because two URL bars can open
   *  it (the hero's and the studio's) while the dialog renders in the studio. */
  pasteOpen: boolean;

  /** Mirrors the URL field so a retry (or deep link) can prefill it. */
  setInput: (input: string) => void;
  setClips: (clips: ViralClip[]) => void;
  clearClips: () => void;
  openPaste: () => void;
  closePaste: () => void;
  /** Turn pasted text (YouTube panel, .srt/.vtt, notes) into the active transcript. */
  loadFromPaste: (text: string, label?: string) => { ok: boolean; message: string };
  /** Read a caption track from the visitor's own connection. */
  fetchInBrowser: () => Promise<{ ok: boolean; message: string }>;
  extract: (input: string) => Promise<void>;
  retry: () => Promise<void>;
  loadDemo: () => Promise<void>;
  reset: () => void;
}

export const useTranscriptStore = create<TranscriptState>((set, get) => ({
  status: "idle",
  input: "",
  transcript: null,
  metadata: null,
  clips: [],
  error: null,
  notice: null,
  diagnostics: [],
  lastFetchedAt: null,
  pasteOpen: false,

  setInput: (input) => set({ input }),

  setClips: (clips) => set({ clips }),
  clearClips: () => set({ clips: [] }),

  openPaste: () => set({ pasteOpen: true }),
  closePaste: () => set({ pasteOpen: false }),

  loadFromPaste: (text, label) => {
    try {
      const parsed = parsePastedTranscript(text);
      const stamp = new Date().toISOString();

      set({
        status: "success",
        error: null,
        clips: [],
        lastFetchedAt: Date.now(),
        diagnostics: [],
        // Warnings travel the same channel as fetch notices, so the existing
        // banner renders them without any new UI.
        notice: parsed.warnings.length > 0 ? parsed.warnings.join(" ") : null,
        metadata: {
          videoId: "pasted",
          url: "",
          title: label?.trim() || `Pasted transcript (${describePasteFormat(parsed.format)})`,
          author: "",
          thumbnailUrl: "",
          durationSeconds: parsed.durationSeconds,
        },
        transcript: {
          videoId: "pasted",
          title: label?.trim() || `Pasted transcript (${describePasteFormat(parsed.format)})`,
          url: "",
          language: "und",
          languageLabel: describePasteFormat(parsed.format),
          isAutoGenerated: false,
          source: "paste",
          strategy: `paste:${parsed.format}`,
          segments: parsed.segments,
          text: parsed.text,
          wordCount: parsed.wordCount,
          characterCount: parsed.characterCount,
          durationSeconds: parsed.durationSeconds,
          fetchedAt: stamp,
        },
      });

      const lines = `${parsed.segments.length} line${parsed.segments.length === 1 ? "" : "s"}`;
      return {
        ok: true,
        message: parsed.timed
          ? `Loaded ${lines} with timestamps — seeking and clip ranges work.`
          : `Loaded ${lines} without timestamps — reading and exporting work; seeking needs timestamps.`,
      };
    } catch (error) {
      const message =
        error instanceof Error ? error.message : "That transcript could not be read.";
      return { ok: false, message };
    }
  },

  fetchInBrowser: async () => {
    // A failed extract clears metadata, but the URL the visitor typed is still
    // in the store — that is the video whose captions we should ask for.
    const stored = get().metadata?.videoId;
    const videoId =
      stored && stored !== "pasted" ? stored : parseYouTubeUrl(get().input)?.videoId;
    if (!videoId) {
      return { ok: false, message: "Load a video first, then fetch its captions from your connection." };
    }
    if (!stored || stored === "pasted") {
      set({
        metadata: {
          videoId,
          url: `https://www.youtube.com/watch?v=${videoId}`,
          thumbnailUrl: "",
        },
      });
    }

    set({ status: "loading", error: null });
    const result = await fetchCaptionsInBrowser(videoId, { lang: get().transcript?.language });

    if (!result.ok) {
      set({
        status: "error",
        diagnostics: result.attempts,
        error: {
          code: "blocked",
          message: result.reason,
          hint: "YouTube does not always allow a page to read captions directly. Open the video, choose \u201cShow transcript\u201d, copy it all, and paste it here — that path always works.",
          diagnostics: result.attempts,
        },
      });
      return { ok: false, message: result.reason };
    }

    const text = result.segments.map((segment) => segment.text).join(" ");
    set((state) => ({
      status: "success",
      error: null,
      clips: [],
      diagnostics: result.attempts,
      notice: "Captions came from your own connection — this server's IP is blocked by YouTube, but yours is not.",
      lastFetchedAt: Date.now(),
      transcript: state.transcript
        ? {
            ...state.transcript,
            source: "browser",
            strategy: `browser:${result.format}`,
            language: result.language,
            languageLabel: `${result.language} (from your browser)`,
            segments: result.segments,
            text,
            wordCount: countWords(text),
            characterCount: text.length,
            durationSeconds: result.segments.at(-1)?.end ?? 0,
            fetchedAt: new Date().toISOString(),
          }
        : null,
    }));
    return { ok: true, message: "Captions loaded from your connection." };
  },

  extract: async (input: string) => {
    const trimmed = input.trim();
    if (!trimmed) return;

    set({
      status: "loading",
      input: trimmed,
      error: null,
      notice: null,
      diagnostics: [],
      // Keep the previous transcript visible while loading so the layout
      // doesn't collapse and re-flow on every fetch.
    });

    try {
      const result = await extractTranscriptAction(trimmed);
      applyResult(result, set);
    } catch (error) {
      set({
        status: "error",
        transcript: null,
        metadata: null,
        error: {
          code: "unknown",
          message:
            error instanceof Error
              ? error.message
              : "The request failed before it reached the server.",
          hint: "Check your connection and try again.",
        },
      });
    }
  },

  retry: async () => {
    const { input } = get();
    if (input) await get().extract(input);
  },

  loadDemo: async () => {
    set({ status: "loading", error: null, notice: null, diagnostics: [] });
    try {
      const result = await loadDemoTranscriptAction();
      applyResult(result, set);
    } catch {
      set({
        status: "error",
        error: {
          code: "unknown",
          message: "Could not load the demo transcript.",
        },
      });
    }
  },

  reset: () =>
    set({
      status: "idle",
      input: "",
      transcript: null,
      metadata: null,
      clips: [],
      error: null,
      notice: null,
      diagnostics: [],
      lastFetchedAt: null,
      pasteOpen: false,
    }),
}));

type Setter = (partial: Partial<TranscriptState>) => void;

function applyResult(result: FetchTranscriptResult, set: Setter) {
  if (result.ok) {
    set({
      status: "success",
      transcript: {
        ...result.transcript,
        ...(result.metadata.title ? { title: result.metadata.title } : {}),
      },
      metadata: result.metadata,
      clips: [],
      error: null,
      notice: result.notice ?? null,
      diagnostics: result.diagnostics ?? [],
      lastFetchedAt: Date.now(),
    });
    return;
  }

  set({
    status: "error",
    transcript: null,
    metadata: null,
    clips: [],
    notice: null,
    diagnostics: result.diagnostics ?? [],
    error: {
      code: result.error,
      message: result.message,
      ...(result.hint ? { hint: result.hint } : {}),
      ...(result.diagnostics ? { diagnostics: result.diagnostics } : {}),
    },
  });
}
