/**
 * ─────────────────────────────────────────────────────────────────────────────
 *  Fetch captions from the visitor's own connection.
 * ─────────────────────────────────────────────────────────────────────────────
 *  The server-side ladder is limited by the *server's* IP: from Vercel (and any
 *  datacenter range) YouTube answers `LOGIN_REQUIRED — Sign in to confirm you're
 *  not a bot`, while the very same request from a home connection succeeds. So
 *  when the server reports a host block, the browser — sitting on the visitor's
 *  own network — is the better place to ask.
 *
 *  Two honest caveats, both surfaced to the user rather than hidden:
 *   • This depends on YouTube allowing a cross-origin (CORS) read of the caption
 *     endpoint. It may refuse; that is a dead end we report, not an error we
 *     dress up.
 *   • The browser first asks YouTube's player endpoint for a signed track, then
 *     tries unsigned timedtext in json3, srv3 and VTT formats. Each route has a
 *     short timeout, so a refusal costs a moment and nothing else.
 */
import { parseCaptionBody } from "@/lib/youtube/parse";
import { normalizeSegments } from "@/lib/youtube/normalize";
import { PRIMARY_CLIENT, withCaptionFormat, unsignedTimedTextUrl } from "@/lib/youtube/clients";
import type { TranscriptSegment } from "@/lib/types";
import { fetchCaptionsDirect, describeDiagnostics } from "@/lib/youtube/captions";
import { connectorFetch, detectConnector } from "@/lib/connector/client";

export interface BrowserCaptionFailure {
  ok: false;
  /** Short, user-facing reason. */
  reason: string;
  /** Every attempt, so the UI can show what was tried (same shape as the server). */
  attempts: string[];
}

export interface BrowserCaptionSuccess {
  ok: true;
  segments: TranscriptSegment[];
  format: string;
  language: string;
  attempts: string[];
  /** "connector" = through the TranStudio Connector add-on; "direct" = plain CORS read. */
  via?: "connector" | "direct";
  languageLabel?: string;
  isAutoGenerated?: boolean;
  title?: string;
  author?: string;
}

export type BrowserCaptionResult = BrowserCaptionSuccess | BrowserCaptionFailure;

/** Ordered best-first: real JSON, then the two XML dialects, then WebVTT. */
const FORMATS = ["json3", "srv3", "vtt"] as const;

async function timedFetch(
  url: string,
  timeoutMs: number,
  init: RequestInit = {},
): Promise<Response> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  try {
    return await fetch(url, {
      ...init,
      // No cookies: a logged-in YouTube session is not required for public
      // captions, and omitting credentials keeps this a plain CORS read.
      credentials: "omit",
      signal: controller.signal,
    });
  } finally {
    clearTimeout(timer);
  }
}

interface BrowserCaptionCandidate {
  label: string;
  base: string;
  language?: string;
}

interface PlayerCaptionTrack {
  baseUrl?: string;
  languageCode?: string;
  kind?: string;
  name?: { simpleText?: string };
}

interface BrowserPlayerResponse {
  captions?: {
    playerCaptionsTracklistRenderer?: {
      captionTracks?: PlayerCaptionTrack[];
    };
  };
}

/**
 * Ask YouTube's public player endpoint from the visitor's browser. This is a
 * second browser-native route: unlike unsigned timedtext, it can reveal the
 * signed caption URL for videos whose track URL is not predictable. YouTube
 * may refuse the CORS preflight; that is recorded and the unsigned route still
 * gets its chance.
 */
async function findBrowserPlayerTracks(
  videoId: string,
  lang: string | undefined,
  timeoutMs: number,
  attempts: string[],
): Promise<BrowserCaptionCandidate[]> {
  const endpoint =
    `https://www.youtube.com/youtubei/v1/player?key=${PRIMARY_CLIENT.apiKey}&prettyPrint=false`;

  try {
    const response = await timedFetch(endpoint, timeoutMs, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({
        context: PRIMARY_CLIENT.context,
        videoId,
        contentCheckOk: true,
        racyCheckOk: true,
      }),
    });

    if (!response.ok) {
      attempts.push(`✗ browser · player — HTTP ${response.status}`);
      return [];
    }

    const payload = (await response.json()) as BrowserPlayerResponse;
    const tracks = payload.captions?.playerCaptionsTracklistRenderer?.captionTracks ?? [];
    const usable = tracks.filter(
      (track): track is PlayerCaptionTrack & { baseUrl: string; languageCode: string } =>
        Boolean(track.baseUrl && track.languageCode),
    );

    if (usable.length === 0) {
      attempts.push("✗ browser · player — no caption tracks exposed");
      return [];
    }

    const wanted = lang?.toLowerCase();
    const baseWanted = wanted?.split("-")[0];
    usable.sort((left, right) => {
      const score = (track: PlayerCaptionTrack & { languageCode: string }) => {
        const code = track.languageCode.toLowerCase();
        if (wanted && code === wanted) return 0;
        if (baseWanted && code === baseWanted) return 1;
        if (track.kind === "asr") return 3;
        return 2;
      };
      return score(left) - score(right);
    });

    const selected = usable.slice(0, 3);
    attempts.push(
      `✓ browser · player — ${usable.length} caption tracks, trying ${selected.length}`,
    );
    return selected.map((track) => ({
      label: `player:${track.languageCode}${track.kind === "asr" ? " (auto-generated)" : ""}`,
      base: track.baseUrl,
      language: track.languageCode,
    }));
  } catch (error) {
    const detail = error instanceof Error ? error.message : "Failed to fetch";
    attempts.push(
      `✗ browser · player — ${detail}. YouTube may have refused the browser CORS request.`,
    );
    return [];
  }
}

/**
 * Run the full server caption ladder from the visitor's own connection, via
 * the TranStudio Connector add-on. Resolves to `null` when the add-on is not
 * installed, so callers can fall through to the plain browser read.
 */
export async function fetchCaptionsViaConnector(
  videoId: string,
  options: { lang?: string; deadlineMs?: number; detectTimeoutMs?: number } = {},
): Promise<BrowserCaptionResult | null> {
  const version = await detectConnector(options.detectTimeoutMs);
  if (!version) return null;

  const result = await fetchCaptionsDirect(videoId, {
    lang: options.lang,
    fetcher: connectorFetch,
    timeoutMs: 9_000,
    deadlineMs: options.deadlineMs ?? 25_000,
  });
  const attempts = describeDiagnostics(result.diagnostics).map((line) => `${line} (via Connector ${version})`);

  if (!result.ok) {
    return {
      ok: false,
      reason: result.videoUnavailable
        ? result.videoUnavailable
        : "The TranStudio Connector reached YouTube, but no captions came back for this video.",
      attempts,
    };
  }

  return {
    ok: true,
    via: "connector",
    segments: result.segments,
    format: result.format,
    language: result.language,
    languageLabel: result.languageLabel,
    isAutoGenerated: result.isAutoGenerated,
    ...(result.title ? { title: result.title } : {}),
    ...(result.author ? { author: result.author } : {}),
    attempts,
  };
}

/**
 * Try to read a caption track directly from the browser.
 *
 * `captionBaseUrl` is the signed URL from a player response when we have one
 * (it is language-specific); otherwise the unsigned endpoint is tried for the
 * requested language and then English.
 */
export async function fetchCaptionsInBrowser(
  videoId: string,
  options: { lang?: string; captionBaseUrl?: string; timeoutMs?: number } = {},
): Promise<BrowserCaptionResult> {
  const timeoutMs = options.timeoutMs ?? 8_000;
  const attempts: string[] = [];

  const candidates: BrowserCaptionCandidate[] = [];
  if (options.captionBaseUrl) {
    candidates.push({
      label: "your player's caption track",
      base: options.captionBaseUrl,
      language: options.lang,
    });
  } else {
    // Prefer a signed track discovered from the visitor's own player request.
    // If YouTube refuses that CORS request, the unsigned candidates below still
    // run exactly as before.
    candidates.push(...(await findBrowserPlayerTracks(videoId, options.lang, timeoutMs, attempts)));
  }

  const language = options.lang?.toLowerCase();
  const languages = Array.from(
    new Set([language, language?.split("-")[0], "en"].filter(Boolean)),
  ) as string[];
  for (const code of languages) {
    candidates.push({
      label: `${code} (auto-generated allowed)`,
      base: unsignedTimedTextUrl(videoId, code),
      language: code,
    });
  }

  for (const candidate of candidates) {
    for (const format of FORMATS) {
      const url = withCaptionFormat(candidate.base, format);
      try {
        const response = await timedFetch(url, timeoutMs);
        if (!response.ok) {
          attempts.push(`✗ ${candidate.label} · ${format} — HTTP ${response.status}`);
          continue;
        }

        const body = await response.text();
        if (!body.trim()) {
          attempts.push(`✗ ${candidate.label} · ${format} — empty`);
          continue;
        }

        const parsed = parseCaptionBody(body);
        if (parsed.empty) {
          attempts.push(`✗ ${candidate.label} · ${format} — parsed as ${parsed.format}, no text`);
          continue;
        }

        const normalized = normalizeSegments(parsed.segments, { forceUnit: parsed.unit });
        if (normalized.segments.length === 0) {
          attempts.push(`✗ ${candidate.label} · ${format} — no usable lines`);
          continue;
        }

        attempts.push(`✓ ${candidate.label} · ${parsed.format} — ${normalized.segments.length} lines`);
        return {
          ok: true,
          via: "direct",
          segments: normalized.segments,
          format: parsed.format,
          language: candidate.language ?? candidate.label.split(" ")[0],
          attempts,
        };
      } catch (error) {
        const detail = error instanceof Error ? error.message : "failed";
        // A CORS refusal and a network failure both land here; the browser does
        // not tell page scripts which one it was, so say so plainly.
        attempts.push(
          `✗ ${candidate.label} · ${format} — ${detail}. If every line says "Failed to fetch", YouTube did not allow this page to read captions; use the paste option instead.`,
        );
      }
    }
  }

  return {
    ok: false,
    reason:
      "The browser could not read YouTube's captions. YouTube, CORS, or the network may have refused the request.",
    attempts,
  };
}
